### ISSUE TITLE
Symbol Editor interface is different between 2525D and 2525C_B2

### ISSUE THREAD

**Issue by elinz** [Esri/military-symbol-editor-addin-wpf#101]
Testing pull request #98 

For example, if I have 2525C_B2 selected then the editor has the tabs on a single row...
![image](https://cloud.githubusercontent.com/assets/4635490/19980626/fa2b3906-a1bb-11e6-9db0-c5147f8d85cb.png)

If I have 2525D selected then the editor has the tabs on multiple rows...
![image](https://cloud.githubusercontent.com/assets/4635490/19980668/2bd6d898-a1bc-11e6-9865-31eb53550f85.png)

Also 2525C_B2 has a SymbolAttributeSet dialog on the bottom of various tabs that I didn't see on the tabs for 2525D...
![image](https://cloud.githubusercontent.com/assets/4635490/19980720/55f13808-a1bc-11e6-975f-840d0e177302.png)

Should the interfaces be the same for both symbol specifications?

**Comment by csmoore** [comment]
The tabs arrangement should only be dependent on the panel size (the 2 sizes look different above, 1st is wider).

The SymbolAttributeSet should be visible whenever there is an active item selected and also should not be dependent on the standard (to test in D, select a search or favorite item then scroll down).

**Comment by elinz** [comment]
@csmoore Oops. Yes, total user error on my part. Closing this issue. Thanks.
