### ISSUE TITLE
Symbol preview on Search tab reflecting the selected feature on map and not selected entry in Search list

### ISSUE THREAD

**Issue by elinz** [Esri/military-symbol-editor-addin-wpf#102]
Testing pull request #98 

Selected spec 2525C_B2.

On Search tab, performed search on "infantry", selected an entry in the list...
![image](https://cloud.githubusercontent.com/assets/4635490/19981047/7fe09d42-a1bd-11e6-81cb-03025a332e54.png)

Then selected a feature on the map...
![image](https://cloud.githubusercontent.com/assets/4635490/19981098/b6029bc8-a1bd-11e6-90ab-87d0075ce329.png)

And the symbol preview on the Search tab switched to the symbol for the selected feature on the map...
![image](https://cloud.githubusercontent.com/assets/4635490/19981133/e0a4155a-a1bd-11e6-927c-11c139adde2a.png)

I believe the intent for the Search tab is to always display the symbol for the selected entry in the search list.

**Comment by csmoore** [comment]
Right now (even before the PR) - selecting an item on the map automatically loads that symbol into the addin. 

We can:

1. Disable this behavior when on the Search and Favorite tab - but the user would need to reselect if they move to another tab and wanted the selected item.
2. Automatically open the modify tab whenever a selection occurs (but there may be cases where they would want to stay on the symbol or label tab and make another selection)
3. Something else?

Just let me know the preferred behavior

**Comment by Dbarnes1** [comment]
I'm unable to reproduce this exact issue with 2525Bc2 settings so I'm not sure what I'm doing differently, but for me the issue is I search for a symbol in the search pane, see that preview, and when I select a feature on the map the preview disappears and neither symbol preview exists in the search pane. @csmoore did you update the symbol editor this morning to do this?  I think option 1 outlined above is our best bet, although I'm not sure this would apply to the favorites tab (favorites tab is working fine for me)

**Comment by Dbarnes1** [comment]
@csmoore further conversations have affirmed my opinion that we should go with your option 1 in regards to the search tab. I'm not sure who would go from the modify to the search tab, as they are separate workflows/ways to use the add-in.

**Comment by csmoore** [comment]
Just summarizing the discussion (let me know if not correct): 

* Currently the addin loads a symbol's state into the addin whenever a valid military symbol is selected on the map
* Change to disable this load behavior whenever on the search tab

**Comment by csmoore** [comment]
Addressed in #121 - the change was:

1. Disables map feature selection from search tab
2. Clears style search selection if a feature or a favorite has been selected on another tab
    a. So user has to reselect the search list item when they return to the search tab

**Comment by elinz** [comment]
@csmoore @Dbarnes1 Validated on single addin built 04 Jan 2017 13:38. Closing issue.
