### ISSUE TITLE
Enter Coordinate Tab Enhancements

### ISSUE THREAD

**Issue by csmoore** [Esri/military-symbol-editor-addin-wpf#104]
This tab is a little difficult to use, to know:

1. Where the coordinate you entered is on the map
2. If the coordinate is at the desired/expected location before you add the symbol
3. If/why the entered coordinate failed

It would be good to add a Flash or Zoom To button on this tab to find the coordinate on the map and add some status message feedback on failures

**Comment by csmoore** [comment]
Agreed to move to v.next milestone at sprint review

**Comment by csmoore** [comment]
A button was added in #129 to the Coordinate Tab to Mark/Zoom To (Last) Coordinate Entered 

![image](https://cloud.githubusercontent.com/assets/3090809/21832385/c20bff0e-d778-11e6-85f4-253541aa310c.png)

**Comment by csmoore** [comment]
@Dbarnes1 - would you mind verifying/taking a look at this - just to get a second set of eyes/opinion for how this works.

**Comment by joebayles** [comment]
@csmoore @Dbarnes1
- Mark/Zoom to Coordinate button:
  - The end drops off the button if you don't have the pane wide enough.
  - Marks and _pans,_ but doesn't _zoom._
- SymbolAttributeSet
  - Words aren't spaced out, except for colon, which shouldn't be.
  - Left-hand column (attributes) are still white text on white.
- Other dark theme issues:
  - Control Measures and other black lines with no background show poorly against dark background.
![image](https://cloud.githubusercontent.com/assets/5016557/21863290/aff4c110-d7f1-11e6-9d32-e7bf0f55da13.png)
  - Buttons don't convert to dark background.

![image](https://cloud.githubusercontent.com/assets/5016557/21863236/7152cba0-d7f1-11e6-9f28-9641a62eff90.png)

... sorry for the unsolicited opinion, and I apologize if any of these issues are logged elsewhere.

**Comment by csmoore** [comment]
@joebayles - this is good feedback, thanks for testing. Dark mode being done in #124 - but I can make these other changes - here is how it will look (changes in highlighter), just to make sure there is agreement:

![image](https://cloud.githubusercontent.com/assets/3090809/21866616/f110fa98-d818-11e6-93fd-d031428d823b.png)

**Comment by joebayles** [comment]
No problem @csmoore , happy to.

A few things I've noticed:
- I'd remove the parentheteses from Coordinate(s).
- I'd also not say coordinate on the second button.
- Maybe change them to "Add Point to Map" and "Mark/Pan to Point"?
- If possible, center the buttons below the coordinate input.

- Very minor thing, but remove the space between Attributes and the colon.
- Change the buttons to support dark theme.

I know these aren't all necessary V-Next changes, but I'll let you decide. Otherwise, looks great.

**Comment by csmoore** [comment]
@joebayles - I had a look at the new comments above and added some justification inline ("CSM") - feel free to open a new issue for any you feel strongly about - and thanks for sanity testing & providing feedback

**Comment by joebayles** [comment]
Not seeing any inline comments, but OK.

**Comment by csmoore** [comment]
@joebayles - sorry forgot to hit `update` button - there now
