### ISSUE TITLE
 For Add-In with 2525c_b2 settings, default information model added named 2525C

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/military-symbol-editor-addin-wpf#105]
Military Symbol Editor Add-In
Pro 1.2
Set to 2525c_b2

to reproduce: 
- downloaded the Add-In (including plug-in install files)
- open it in a blank pro project. 
- follow prompt to add military overlay information model when you get warning that Add-In is disabled

It adds information model named with 2525C. The setting of the 2525c_b2 stylx that we are releasing with this version of military tools defaults to 2525b change 2 (this setting is in stylx meta table). 

Solution: The information model that the Add-In adds to a new project should be named 2525 B Change 2. Because the schema's and layers are the same for both C and B Change 2, I think the quickest fix would be taking [this file](https://github.com/Esri/military-features-data/tree/v.next/data/mil2525c_b2/overlay_templates) and replacing references of 2525C with 2525 B Change 2. 

Screenshot below illustrates that a user who is in an organization that uses B Change 2 and is using our editor would view a group layer and a feature dataset called mil2525C:
![image](https://cloud.githubusercontent.com/assets/13024357/20016017/0234c2ba-a27b-11e6-8607-aa9b29ea7694.png)

**Comment by csmoore** [comment]
@Dbarnes1 - I can update when a new version of the current lpkx from https://github.com/Esri/military-features-data/tree/v.next/data/mil2525c_b2/overlay_templates is provided

**Comment by Dbarnes1** [comment]
https://github.com/Esri/military-features-data/pull/251

This new lpkx should work- references to C got changed to B Change 2.

**Comment by csmoore** [comment]
Ready to verify on next daily

**Comment by Dbarnes1** [comment]
@csmoore verified, closing. Thanks!
