### ISSUE TITLE
For Pro 1.2 version, consider removing references to 2525C

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/military-symbol-editor-addin-wpf#106]
Surfacing the fact that one stylx supports two dictionaries might confuse the audience that wants to use the symbol editor. Should we get rid of references to 2525C all together for this release of the add-in? 

Here are our options:
1. Provide doc (both online and offline) to users to edit the meta table in the stylx using a sqlite editor so they can switch between 2525C and 2525B Change 2. In addition, enhance the symbol editor for this release so that it recognizes when the settings of the stylx are set to either 2525C or 2525B Change 2. This might require a high level of effort. 
2. Remove text that references 2525C in the Add-In for Pro 1.2 release. At Pro 1.4, this setting will be supported in the symbology pane and can be enhanced in the template and the add-in. 

I guess the key question here is do we have a need to support 2525c at the next release, or can this wait until the release of Pro 1.4. @nfeuerstein @lfunkhouser I think you guys might need to weigh in on this before we decide. 
![image](https://cloud.githubusercontent.com/assets/13024357/20016065/270b7d0e-a27b-11e6-99a5-3a599f329a3a.png)

**Comment by Dbarnes1** [comment]
according to sprint review feedback this needs to be completed

**Comment by csmoore** [comment]
This was updated in https://github.com/csmoore/military-symbol-editor-addin-wpf/commit/0bb47ef577d02868392469bfcda3cd490ca38424 ex: 

![image](https://cloud.githubusercontent.com/assets/3090809/20122340/ff38709e-a5e4-11e6-886b-b485015343aa.png)

**Comment by csmoore** [comment]
Ready to verify on next daily

**Comment by Dbarnes1** [comment]
@csmoore verified, thanks!
