### ISSUE TITLE
Modify pane symbol preview doesn't refresh once you save edits

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/military-symbol-editor-addin-wpf#108]
I'm using Pro 1.2 and the 2525c_b2 version of the add-in.

To reproduce: 
1. Select a feature in the modify pane: 
![image](https://cloud.githubusercontent.com/assets/13024357/20019269/a2e257ce-a288-11e6-85ae-5d111b742531.png)

2. edit the symbol in the Symbol pane and save your edits:
![image](https://cloud.githubusercontent.com/assets/13024357/20019281/c10ab156-a288-11e6-9c8d-34436b34462c.png)

3. go back to the modify pane and see that the symbol preview still shows the symbol you selected pre-editing:

![image](https://cloud.githubusercontent.com/assets/13024357/20019308/ea962f8c-a288-11e6-8503-a33707469292.png)

This is confusing, but not a showstopper bug by any means.

**Comment by csmoore** [comment]
Addressed in #156, by:

1. Flashing/reselecting feature on "Save Edits"
2. This selects/flashes the feature and returns you to the modify pane

Which seems like a nice workflow/feedback on save

**Comment by ACueva** [comment]
Verified using original steps.
![2017-05-30_14-46-12](https://cloud.githubusercontent.com/assets/3093940/26606445/ccf003a2-4546-11e7-93ab-c0385b158997.png)

**Comment by dfoll** [comment]
tested on 1526 .... this works the way that @csmoore says it does, i am not seeing the behavior that @Dbarnes1 originally logged the issue about, and i agree with @csmoore that it's just a nice touch that you go back to the modify pane. closing
