### ISSUE TITLE
Symbol Preview missing exact icons for 2525B Change 2

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/military-symbol-editor-addin-wpf#110]
From release notes/known issues:

*Image previews are using the 2525D icons so a small set of icons will be different in the preview from how they display on the map. a. Justification: Dictionary Renderer image preview did not get added to the Pro API until 1.3 (and sizes > 32 pixels until 1.4) so we are still using a custom image preview solution.*

*Required change:*
*1. Wait until 1.4 to implement -or- ii. Spend a 1-2 weeks updating the custom solution to use C/B2 icons*
*2. Spend a 1-2 weeks updating the custom solution to use C/B2 icons*

List of affected symbols: 

|Airspace Control Points : Antisubmarine Warfare- Rotary Wing (2525B)|G-G-GPAH--|
|---|---|
|Airspace Control Points : ASW (Helo and F/W) Station (2525B)|G-G-GPAA--|
|Airspace Control Points : Corridor Tab (2525B)|G-G-GPAC--|
|Airspace Control Points : Marshall (2525B)|G-G-GPAM--|
|Airspace Control Points : Replenishment Station (2525B)|G-G-GPAL--|
|Airspace Control Points : Rescue (2525B)|G-G-GPAR--|
|Airspace Control Points : Strike Initial Point (2525B)|G-G-GPAS--|
|Airspace Control Points : TACAN (2525B)|G-G-GPAT--|
|Airspace Control Points : Tanking (2525B)|G-G-GPAK--|
|Airspace Control Points : Tomcat (2525B)|G-G-GPAO--|
|Civilian (Air) : Rotary Wing|S-A-CH----|
|Civilian (Land Civilian) : Organization or Group : Organization : Targeted Individual or Organization|O-G-C-----|
|Civilian (Sea Surface) : Merchant Ship : Cargo- General|S-S-XMC---|
|Civilian (Sea Surface) : Merchant Ship : Ferry|S-S-XMF---|
|Civilian (Sea Surface) : Merchant Ship : Hovercraft|S-S-XH----|
|Civilian (Sea Surface) : Merchant Ship : Oiler/Tanker|S-S-XMO---|
|Civilian (Sea Surface) : Merchant Ship : Passenger|S-S-XMP---|
|Civilian (Sea Surface) : Merchant Ship : Roll On/Roll Off|S-S-XMR---|
|Civilian (Sea Surface) : Merchant Ship : Tug- Ocean Going|S-S-XMTU--|
|Civilian Vehicle|S-G-EVC---|
|Civilian Vehicle : Tractor Trailer with Flatbed : Small/Light|S-G-EVCFL-|
|Command and Control : Signal : LCCP|S-G-UUSCL-|
|Command and Control : Signal : Radio Relay|S-G-UUSRW-|
|Command and Control : Signal : Small Extension Node|S-G-UUSMS-|
|Command and Control : Signal : Telephone Switch|S-G-UUSW--|
|Command and Control : Special C2 Headquarters Component|S-G-UH----|
|Command and Control : Tactical Satellite|S-G-UCDSC-|
|Command and Control Points : Waypoint|G-G-GPPW--|
|Engineer Equipment : Bridge|S-G-EVEB--|
|Engineer Equipment : Mine Laying Equipment|S-G-EVEM--|
|Fires : Air Defense : Capability : Short Range|S-G-UCDS--|
|Fires : Air Defense : Capability : Target Acquisition|S-G-UCDT--|
|Fires : Air Defense : Composite|S-G-UCDC--|
|Fires : Air Defense : Main Gun System|S-G-UCDG--|
|Fires : Air Defense : Missile : Avenger|S-G-UCDMLA|
|Fires : Air Defense : Missile : Capability : Ground Station Module|S-G-UCDH--|
|Fires : Air Defense : Missile : Capability : Heavy|S-G-UCDMH-|
|Fires : Air Defense : Missile : Capability : Light|S-G-UCDML-|
|Fires : Air Defense : Missile : Capability : Medium|S-G-UCDMM-|
|Fires : Air Defense : Missile : Hawk|S-G-UCDHH-|
|Fires : Air Defense : Missile : Patriot|S-G-UCDHP-|
|Fires : Air Defense : Short Range : Stinger|S-G-UCDSS-|
|Fires : Air Defense : Short Range : Vulcan|S-G-UCDSV-|
|Fires : Air Defense : Theater/Echelons Above Corps Support : Capability : Missile|S-G-UCDO--|
|Fires : Field Artillery : Capability : Radar|S-G-UCFTR-|
|Fires : Field Artillery : Capability : Single Rocket Launcher : Mobility : Wheeled|S-G-UCFRSR|
|Fires : Field Artillery : Capability : Sound Ranging|S-G-UCFTS-|
|Fires : Field Artillery : Capability : Target Acquisition|S-G-UCFT--|
|Fires : Field Artillery : Capability : Target Acquisition : Capability : Optical (Flash)|S-G-UCFTF-|
|Fires : Field Artillery : Howitzer/Gun|S-G-UCFH--|
|Fires : Field Artillery : Howitzer/Gun : Amphibious|S-G-UCFHX-|
|Fires : Field Artillery : Mortar : Amphibious|S-G-UCFML-|
|Fires : Field Artillery : Observer : Dismounted|S-G-UCFTCD|
|Fires : Field Artillery : Rocket|S-G-UCFR--|
|Fires : Field Artillery : Self-propelled : Capability : Multiple Rocket Launcher : Mobility : Wheeled|S-G-UCFRMR|
|Fires : Field Artillery : Target Acquisition : Capability : Multiple Rocket Launcher : Mobility : Towed|S-G-UCFRMT|
|Fires : Field Artillery Observer|S-G-UCFTC-|
|Fires : Missile : Capability : Strategic|S-G-UCMS--|
|Fires : Missile : Capability : Tactical|S-G-UCMT--|
|Fires : Missile|S-G-UCM---|
|Fires : Survey : Capability : Light|S-G-UCFSL-|
|Fires : Survey : Capability : Mountain|S-G-UCFSO-|
|Fires : Survey : Mobility : Air Mobile/Air Assault (US Only)|S-G-UCFSS-|
|Fires : Survey : Mobility : Airborne|S-G-UCFSA-|
|Fires : Survey|S-G-UCFS--|
|Incident : Criminal Activity Incident : Arson (2525B)|O-V-A-----|
|Infrastructure : Energy Facility : Electric Power : CBRN Type : Nuclear|S-G-IUEN--|
|Infrastructure : Energy Facility : Electric Power : Dam|S-G-IUED--|
|Infrastructure : Energy Facility : Electric Power : Fossil Fuel|S-G-IUEF--|
|Infrastructure : Transportation : Sea Port/Naval Base|S-G-IBN---|
|Infrastructure : Transportation : Ship Yard|S-G-IMS---|
|Installation : Mass Grave Site|O-L-M-----|
|Installation : Nuclear (Non CBRN Defense) |S-G-IMF---|
|Installation : Nuclear (Non CBRN Defense) : No Category Listed : Weapons Grade|S-G-IMFPW-|
|Installation : Processing Facility|S-G-IP----|
|Installation : Processing Facility : Decontamination|S-G-IPD---|
|Installation : Raw Material|S-G-IR----|
|Installation : Utility|S-G-IU----|
|Installation : Utility : Research|S-G-IUR---|
|Installation : Utility : TELECOM|S-G-IUT---|
|Intelligence : Electronic Ranging|S-G-UUSX--|
|Intelligence : Electronic Warfare : Armored : Wheeled|S-G-UUMSEA|
|Intelligence : Electronic Warfare : Jamming|S-G-UUMSEJ|
|Intelligence : Military Intelligence : Capability : Sensor|S-G-UUMRS-|
|Intelligence : Military Intelligence : Capability : Sensor Control Module (SCM)|S-G-UUMRSS|
|Land Mines : Land Mine|S-G-EXM---|
|Maneuver Points : Observation Post/Outpost (Specified) : Sensor Outpost/Listening Post|G-G-DPOS--|
|Maritime Points : Data Link Reference Point (2525B)|G-G-GPRD--|
|Maritime Points : Marshall Point|G-G-GPRM--|
|Maritime Points : Navigational Reference Point|G-G-GPRN--|
|Maritime Points : Position and Intended Movement (PIM) Route |G-G-GPOP--|
|Military (Air) : Fixed-Wing : Airborne Command Post (ACP)|S-A-MFD---|
|Military (Air) : Fixed-Wing : Airborne Early Warning (AEW)|S-A-MFRW--|
|Military (Air) : Fixed-Wing : Antisubmarine Warfare|S-A-MFS---|
|Military (Air) : Fixed-Wing : Antisurface Warfare|S-A-MFPN--|
|Military (Air) : Fixed-Wing : Attack/Strike : Military Aircraft Type : Interceptor|S-A-MFFI--|
|Military (Air) : Fixed-Wing : Combat Search and Rescue (CSAR)|S-A-MFH---|
|Military (Air) : Fixed-Wing : Communications|S-A-MFY---|
|Military (Air) : Fixed-Wing : Electronic Support (ES)|S-A-MFRZ--|
|Military (Air) : Fixed-Wing : Photographic Reconnaissance|S-A-MFRX--|
|Military (Air) : Fixed-Wing : Tanker : Re-fueling Capability : Boom-Only|S-A-MFKB--|
|Military (Air) : Fixed-Wing : Tanker : Re-fueling Capability : Drogue-Only|S-A-MFKD--|
|Military (Air) : Fixed-Wing : VSTOL|S-A-MFL---|
|Military (Air) : Rotary-Wing : Military Aircraft Type : Airborne Command Post (ACP)|S-A-MHD---|
|Military (Air) : Rotary-Wing : Military Mission Area : Antisurface Warfare|S-A-MHS---|
|Military (Air) : Rotary-Wing : Military Mission Area : Combat Search and Rescue (CSAR)|S-A-MHH---|
|Military (Air) : Unmanned Aircraft (UA- UAV- UAS- RPV) : Aircraft Type : VSTOL/VTOL|S-A-MFQL--|
|Military (Air) : Unmanned Aircraft (UA- UAV- UAS- RPV) : Military Aircraft Type : Airborne Command Post (ACP)|S-A-MFQD--|
|Military (Air) : Unmanned Aircraft (UA- UAV- UAS- RPV) : Military Aircraft Type : Airborne Early Warning (AEW)|S-A-MFQRW-|
|Military (Air) : Unmanned Aircraft (UA- UAV- UAS- RPV) : Military Mission Area : Antisubmarine Warfare|S-A-MFQS--|
|Military (Air) : Unmanned Aircraft (UA- UAV- UAS- RPV) : Military Mission Area : Antisurface Warfare|S-A-MFQN--|
|Military (Air) : Unmanned Aircraft (UA- UAV- UAS- RPV) : Military Mission Area : Combat Search and Rescue (CSAR)|S-A-MFQH--|
|Military (Air) : Unmanned Aircraft (UA- UAV- UAS- RPV) : Military Mission Area : Electronic Support (ES)|S-A-MFQRZ-|
|Military (Air) : Unmanned Aircraft (UA- UAV- UAS- RPV) : Mission Area : Communications|S-A-MFQY--|
|Military (Air) : Unmanned Aircraft (UA- UAV- UAS- RPV) : Mission Area : Photographic (Reconnaissance)|S-A-MFQRX-|
|Military (Sea Subsurface) : Autonomous Underwater Vehicle (AUV) : Mine Warfare|S-U-SUM---|
|Military (Sea Subsurface) : Nonsubmarine|S-U-SX----|
|Military (Sea Subsurface) : Other Submersible|S-U-SO----|
|Military (Sea Subsurface) : Submarine : Nuclear Powered : Attack|S-U-SNA---|
|Military (Sea Subsurface) : Submarine : Nuclear Powered : Ballistic Missile|S-U-SNB---|
|Military (Sea Subsurface) : Submarine : Other : Surfaced|S-U-SOF---|
|Military (Sea Subsurface) : Submarine : Ship Propulsion : Diesel Electric General|S-U-SC----|
|Military (Sea Subsurface) : Submarine : Ship Propulsion : Nuclear Powered General|S-U-SN----|
|Military (Sea Subsurface) : Submarine : Submarine Confidence : Possible Submarine High 3|S-U-S3----|
|Military (Sea Subsurface) : Submarine : Submarine Confidence : Possible Submarine High 4|S-U-S4----|
|Military (Sea Subsurface) : Submarine : Submarine Confidence : Possible Submarine Low 1|S-U-S1----|
|Military (Sea Subsurface) : Submarine : Submarine Confidence : Possible Submarine Low 2|S-U-S2----|
|Military (Sea Subsurface) : Submarine : Submarine Confidence : Probable Submarine|S-U-SL----|
|Military (Sea Subsurface) : Submarine : Submarine-Surfaced : Ship Propulsion : Diesel Electric General|S-U-SCF---|
|Military (Sea Subsurface) : Submarine : Submarine-Surfaced : Ship Propulsion : Nuclear Powered General|S-U-SNF---|
|Military (Sea Subsurface) : Submarine : Submarine-Surfaced : Submarine Confidence : Certain Submarine|S-U-SR----|
|Military (Sea Subsurface) : Submarine : Weapons Capability : Attack : Ship Propulsion : Diesel Electric General|S-U-SCA---|
|Military (Sea Subsurface) : Submarine : Weapons Capability : Ballistic Missile (Sea Subsurface) : Ship Propulsion : Diesel Electric General|S-U-SCB---|
|Military (Sea Subsurface) : Submarine : Weapons Capability : Guided Missile (Sea Subsurface) : Ship Propulsion : Diesel Electric General|S-U-SCG---|
|Military (Sea Subsurface) : Submarine : Weapons Capability : Guided Missile (Sea Subsurface) : Ship Propulsion : Nuclear Powered General|S-U-SNG---|
|Military (Sea Subsurface) : Submarine : Weapons Capability : Other Guided Missile (Sea Subsurface) : Ship Propulsion : Diesel Electric General|S-U-SCM---|
|Military (Sea Subsurface) : Submarine : Weapons Capability : Other Guided Missile (Sea Subsurface) : Ship Propulsion : Nuclear Powered General|S-U-SNM---|
|Military (Space) : Satellite|S-P-S-----|
|Military (Space) : Space Station|S-P-T-----|
|Military (Space) : Space Vehicle : Crewed|S-P-V-----|
|Military : Submarine : Station|S-U-SS----|
|Military : Submarine : Station : ASW : Submarine|S-U-SSA---|
|Military Combatant : Decoy|S-S-CD----|
|Military Combatant : Hovercraft|S-S-CH----|
|Military Combatant : Mine Warfare Ship : Mine Countermeasures- Support Ship|S-S-CMMA--|
|Military Combatant : Navy Task Organization : Navy Task Force|S-S-GT----|
|Military Combatant : Navy Task Organization : Navy Task Group|S-S-GG----|
|Military Combatant : Navy Task Organization : Navy Task Unit|S-S-GU----|
|Military Combatant : Patrol Boat : Antiship Missile|S-S-CPSUM-|
|Military Combatant : Patrol Boat : USV Control : Autonomous Control|S-S-CPSU--|
|Military Combatant : Patrol Boat : Weapons Capability : Torpedo|S-S-CPSUT-|
|Military Combatant : Station|S-S-S-----|
|Military Combatant : Station : ASW : Ship|S-S-SA----|
|Military Combatant : Station : Picket|S-S-SP----|
|Military Combatant : Surface Combatant- Line : Littoral Combatant Ship : Mission Area : Antisubmarine Warfare (Sea Surface)|S-S-CLLLAS|
|Military Combatant : Surface Combatant- Line : Littoral Combatant Ship : Mission Area : Mine Warfare (Sea Surface)|S-S-CLLLMI|
|Military Combatant : Surface Combatant- Line : Littoral Combatant Ship : Mission Area : Surface Warfare (Sea Surface)|S-S-CLLLSU|
|Military Combatant : Surface Combatant- Line : Littoral Combatant Ship|S-S-CLLL--|
|Military Noncombatant : Auxiliary Ship : Intelligence Collector|S-S-NI----|
|Military Noncombatant : Hovercraft|S-S-NH----|
|Military Noncombatant : Service Craft/Yard|S-S-NS----|
|Military Noncombatant : Station|S-S-NN----|
|Military Noncombatant : Station : Rescue|S-S-NNR---|
|Missile (Air Missile) : Launch Origin : Air : Missile Destination : Space|S-A-WMAP--|
|Missile (Air Missile) : Launch Origin : Subsurface : Missile Destination : Surface|S-A-WMU---|
|Missile (Air Missile) : Launch Origin : Surface : Missile Destination : Subsurface|S-A-WMSU--|
|Missile (Air Missile) : Missile Class : Anti-Ballistic|S-A-WMSB--|
|Movement and Maneuver : Antitank/Antiarmor : Armored : Mobility : Air Mobile/Air Assault (US Only)|S-G-UCAAAS|
|Movement and Maneuver : Antitank/Antiarmor : Mobility : Air Mobile/Air Assault (US Only)|S-G-UCAAS-|
|Movement and Maneuver : Antitank/Antiarmor : Mobility : Air Mobile/Air Assault (US Only) : Mobility : Wheeled|S-G-UCAWS-|
|Movement and Maneuver : Antitank/Antiarmor : Mobility : Air Mobile/Air Assault (US Only) : Neutral|S-G-UCAAS-|
|Movement and Maneuver : Armor/Armored/Mechanized/Self-Propelled/Tracked : Reconnaissance/Cavalry/Scout : Capability : Light|S-G-UCRRL-|
|Movement and Maneuver : Army Aviation/Aviation Rotary Wing : Capability : Command and Control|S-G-UCVRUC|
|Movement and Maneuver : Army Aviation/Aviation Rotary Wing : Capability : Search and Rescue|S-G-UCVS--|
|Movement and Maneuver : Army Aviation/Aviation Rotary Wing : Scout|S-G-UCVRS-|
|Movement and Maneuver : Army Aviation/Aviation Rotary Wing : SOF|S-F-AH----|
|Movement and Maneuver : Aviation Composite|S-G-UCVC--|
|Movement and Maneuver : Aviation Fixed Wing : Mobility : Vertical or Short Take-Off and Landing (VTOL/VSTOL)|S-G-UCVV--|
|Movement and Maneuver : Aviation Fixed Wing : Reconnaissance|S-G-UCVFR-|
|Movement and Maneuver : Aviation Rotary Wing|S-G-UCVR--|
|Movement and Maneuver : Combat : Armor : Wheeled : Airborne|S-G-UCAWA-|
|Movement and Maneuver : Combat : Armor : Wheeled : Amphibious Recovery|S-G-UCAWWR|
|Movement and Maneuver : Combat : Armor : Wheeled : Heavy|S-G-UCAWH-|
|Movement and Maneuver : Combat : Armor : Wheeled : Light|S-G-UCAWL-|
|Movement and Maneuver : Combat : Armor : Wheeled : Medium|S-G-UCAWM-|
|Movement and Maneuver : Combat : Armor : Wheeled : Recovery|S-G-UCAWR-|
|Movement and Maneuver : Infantry : Capability : Naval|S-G-UCIN--|
|Movement and Maneuver : Reconnaissance/Cavalry/Scout : Capability : Long Range|S-G-UCRX--|
|Movement and Maneuver : Reconnaissance/Cavalry/Scout : Capability : Pack Animal|S-G-UCRH--|
|Movement and Maneuver : Reconnaissance/Cavalry/Scout : Cavalry|S-G-UCRV--|
|Movement and Maneuver : Reconnaissance/Cavalry/Scout : Marine : Capability : Division|S-G-UCRRD-|
|Movement and Maneuver : SOF : Capability : Attack 2|S-F-B-----|
|Own Ship|S-S-O-----|
|Protection : CBRN Defense : Capability : Smoke : Capability : Decontamination 2|S-G-UUACC-|
|Protection : CBRN Defense : Mechanized : Capability : Smoke : Capability : Decontamination 2|S-G-UUACCK|
|Protection : CBRN Defense : Motorized : Capability : Smoke : Capability : Decontamination 2|S-G-UUACCM|
|Protection : CBRN Defense : Surveillance Armored : Wheeled|S-G-UUACRS|
|Protection : Combat Support (Maneuver Enhancement)|S-G-UU----|
|Protection : Information Warfare|S-G-UUI---|
|Protection : Law Enforcement|S-G-UUL---|
|Protection : Security : Dismounted|S-G-UCSGD-|
|Protection : Security : Mobility : Riverine|S-G-UCSW--|
|Protection Areas : Minefield : Dummy|G-G-PN----|
|Protection Points : Biological Event|G-M-NEB---|
|Protection Points : Chemical Event|G-M-NEC---|
|Protection Points : Nuclear Event|G-M-NZ----|
|Protection Points : Nuclear Fallout Producing Event|G-M-NF----|
|Sea Mine-General : MILCO|S-U-WMC---|
|Sea Mine-General : MILCO : Floating|S-U-WMFC--|
|Sea Mine-General : MILCO : Ground (Bottom)|S-U-WMGC--|
|Sea Mine-General : MILCO : Moored|S-U-WMMC--|
|Signal Intercept (Air) : Radar : Jammer : Missile Tracking (Air)|I-A-SRMT--|
|Signal Intercept (Air) : Radar : Jammer : Multi-Function (Air)|I-A-SRMF--|
|Signal Intercept (Air) : Radar : Radar : Airborne Intercept|I-A-SRAI--|
|Signal Intercept (Air) : Radar : Radar : Airborne Search and Bombing|I-A-SRAS--|
|Signal Intercept (Air) : Radar : Radar : Controlled Intercept (Air)|I-A-SRC---|
|Signal Intercept (Air) : Radar : Radar : Data Transmission (Air)|I-A-SRD---|
|Signal Intercept (Air) : Radar : Radar : Early Warning (Air)|I-A-SRE---|
|Signal Intercept (Air) : Radar : Radar : Fire Control (Air)|I-A-SRF---|
|Signal Intercept (Air) : Radar : Radar : Identification Friend or Foe (Transponder) (Air)|I-A-SRI---|
|Signal Intercept (Air) : Radar : Radar : Missile Acquisition (Air)|I-A-SRMA--|
|Signal Intercept (Air) : Radar : Radar : Missile Downlink|I-A-SRMD--|
|Signal Intercept (Air) : Radar : Radar : Missile Guidance (Air)|I-A-SRMG--|
|Signal Intercept (Air) : Radar : Radar : Target Acquisition|I-A-SRTA--|
|Signal Intercept (Air) : Radar : Radar : Target Illumination (Air)|I-A-SRTI--|
|Signal Intercept (Air) : Radar : Radar : Target Tracking (Air)|I-A-SRTT--|
|Signal Intercept (Air) : Radar : Radar : Unknown (Air)|I-A-SRU---|
|Signal Intercept (Land) : Communications : Communications : Cellular/Mobile (Land)|I-G-SCC---|
|Signal Intercept (Land) : Communications : Communications : Omni-Line of Sight (LOS) (Land)|I-G-SCO---|
|Signal Intercept (Land) : Communications : Communications : Point-to-Point Line of Sight (LOS) (Land)|I-G-SCP---|
|Signal Intercept (Land) : Communications : Communications : Satellite Uplink (Land)|I-G-SCS---|
|Signal Intercept (Land) : Communications : Communications : Tropospheric Scatter|I-G-SCT---|
|Signal Intercept (Land) : Radar : Jammer : Missile Tracking (Land)|I-G-SRMT--|
|Signal Intercept (Land) : Radar : Jammer : Multi-Function (Land)|I-G-SRMF--|
|Signal Intercept (Land) : Radar : Jammer : Target Acquisition (Land)|I-G-SRTA--|
|Signal Intercept (Land) : Radar|I-G-SRCS--|
|Signal Intercept (Land) : Radar : Radar : Air Traffic Control (Land)|I-G-SRAT--|
|Signal Intercept (Land) : Radar : Radar : Battlefield Surveillance (Land)|I-G-SRB---|
|Signal Intercept (Land) : Radar : Radar : Controlled Approach (Land)|I-G-SRCA--|
|Signal Intercept (Land) : Radar : Radar : Data Transmission (Land)|I-G-SRD---|
|Signal Intercept (Land) : Radar : Radar : Early Warning (Land)|I-G-SRE---|
|Signal Intercept (Land) : Radar : Radar : Fire Control (Land)|I-G-SRF---|
|Signal Intercept (Land) : Radar : Radar : Height Finding (Land)|I-G-SRH---|
|Signal Intercept (Land) : Radar : Radar : Identification Friend or Foe (Interrogator) (Land)|I-G-SRI---|
|Signal Intercept (Land) : Radar : Radar : Meteorological (Land)|I-G-SRMM--|
|Signal Intercept (Land) : Radar : Radar : Missile Acquisition (Land)|I-G-SRMA--|
|Signal Intercept (Land) : Radar : Radar : Missile Guidance (Land)|I-G-SRMG--|
|Signal Intercept (Land) : Radar : Radar : Shell Tracking|I-G-SRS---|
|Signal Intercept (Land) : Radar : Radar : Target Illumination (Land)|I-G-SRTI--|
|Signal Intercept (Land) : Radar : Radar : Target Tracking (Land)|I-G-SRTT--|
|Signal Intercept (Land) : Radar : Radar : Unknown (Land)|I-G-SRU---|
|Signal Intercept (Sea Subsurface) : Communications : Communications : Omni-Line of Sight (LOS) (Sea Subsurface)|I-U-SCO---|
|Signal Intercept (Sea Subsurface) : Communications : Communications : Point-to-Point Line of Sight (LOS) (Sea Subsurface)|I-U-SCP---|
|Signal Intercept (Sea Subsurface) : Communications : Communications : Satellite Uplink (Sea Subsurface)|I-U-SCS---|
|Signal Intercept (Sea Subsurface) : Radar : Jammer : Multi-Function (Sea Subsurface)|I-U-SRM---|
|Signal Intercept (Sea Subsurface) : Radar : Jammer : Target Acquisition (Sea Subsurface)|I-U-SRT---|
|Signal Intercept (Sea Subsurface) : Radar : Radar : Data Transmission (Sea Subsurface)|I-U-SRD---|
|Signal Intercept (Sea Subsurface) : Radar : Radar : Early Warning (Sea Subsurface)|I-U-SRE---|
|Signal Intercept (Sea Subsurface) : Radar : Radar : Surface Search (Sea Subsurface)|I-U-SRS---|
|Signal Intercept (Sea Subsurface) : Radar : Radar : Unknown (Sea Subsurface)|I-U-SRU---|
|Signal Intercept (Sea Surface) : Communications : Air/Land/Sea Surface/Subsurface Communications : Omni-Line of Sight (LOS) (Sea Surface)|I-S-SCO---|
|Signal Intercept (Sea Surface) : Communications : Communications : Cellular/Mobile (Sea Surface)|I-S-SCC---|
|Signal Intercept (Sea Surface) : Communications : Communications : Point-to-Point Line of Sight (LOS) (Sea Surface)|I-S-SCP---|
|Signal Intercept (Sea Surface) : Communications : Communications : Satellite Uplink (Sea Surface)|I-S-SCS---|
|Signal Intercept (Sea Surface) : Radar : Jammer : Missile Tracking (Sea Surface)|I-S-SRMT--|
|Signal Intercept (Sea Surface) : Radar : Jammer : Multi-Function (Sea Surface)|I-S-SRMF--|
|Signal Intercept (Sea Surface) : Radar : Jammer : Target Acquisition (Sea Surface)|I-S-SRTA--|
|Signal Intercept (Sea Surface) : Radar : Radar : Air Traffic Control (Sea Surface)|I-S-SRAT--|
|Signal Intercept (Sea Surface) : Radar : Radar : Anti-Aircraft Fire Control (Sea Surface)|I-S-SRAA--|
|Signal Intercept (Sea Surface) : Radar : Radar : Controlled Approach (Sea Surface)|I-S-SRCA--|
|Signal Intercept (Sea Surface) : Radar : Radar : Controlled Intercept (Sea Surface)|I-S-SRCI--|
|Signal Intercept (Sea Surface) : Radar : Radar : Data Transmission (Sea Surface)|I-S-SRD---|
|Signal Intercept (Sea Surface) : Radar : Radar : Early Warning (Sea Surface)|I-S-SRE---|
|Signal Intercept (Sea Surface) : Radar : Radar : Fire Control (Sea Surface)|I-S-SRF---|
|Signal Intercept (Sea Surface) : Radar : Radar : Height Finding (Sea Surface)|I-S-SRH---|
|Signal Intercept (Sea Surface) : Radar : Radar : Identification Friend or Foe (Interrogator) (Sea Surface)|I-S-SRI---|
|Signal Intercept (Sea Surface) : Radar : Radar : Meteorological (Sea Surface)|I-S-SRMM--|
|Signal Intercept (Sea Surface) : Radar : Radar : Missile Acquisition (Sea Surface)|I-S-SRMA--|
|Signal Intercept (Sea Surface) : Radar : Radar : Missile Guidance (Sea Surface)|I-S-SRMG--|
|Signal Intercept (Sea Surface) : Radar : Radar : Surface Search (Sea Surface)|I-S-SRS---|
|Signal Intercept (Sea Surface) : Radar : Radar : Target Illumination (Sea Surface)|I-S-SRTI--|
|Signal Intercept (Sea Surface) : Radar : Radar : Target Tracking (Sea Surface)|I-S-SRTT--|
|Signal Intercept (Sea Surface) : Radar : Radar : Unknown (Sea Surface)|I-S-SRU---|
|Signal Intercept (Space) : Communications : Communications : Satellite Downlink (Space)|I-P-SCD---|
|Signal Intercept (Space) : Radar : Jammer : Multi-Function (Space)|I-P-SRM---|
|Signal Intercept (Space) : Radar : Jammer : Target Acquisition (Space)|I-P-SRT---|
|Signal Intercept (Space) : Radar : Radar : Data Transmission (Space)|I-P-SRD---|
|Signal Intercept (Space) : Radar : Radar : Earth Surveillance|I-P-SRE---|
|Signal Intercept (Space) : Radar : Radar : Identification Friend or Foe (Transponder) (Space)|I-P-SRI---|
|Signal Intercept (Space) : Radar : Radar : Space (Space)|I-P-SRS---|
|Signal Intercept (Space) : Radar : Radar : Unknown (Space)|I-P-SRU---|
|Sustainment : Laundry/Bath : Corps Support|S-G-USSLC-|
|Sustainment : Laundry/Bath|S-G-USSL--|
|Sustainment : Laundry/Bath : Theater/Echelons Above Corps Support|S-G-USSLT-|
|Sustainment : Maintenance : Corps Support : Capability : Missile|S-G-USXOMC|
|Sustainment : Maintenance : Recovery|S-G-USXR--|
|Sustainment : Maintenance : Recovery : Corps|S-G-USXRC-|
|Sustainment : Maintenance : Recovery : Theater|S-G-USXRT-|
|Sustainment : Maintenance : Theater/Echelons Above Corps Support : Capability : Missile|S-G-USXOMT|
|Sustainment : Medical Treatment Facility : Corps Support : Capability : Veterinary|S-G-USMVC-|
|Sustainment : Medical Treatment Facility : Theater/Echelons Above Corps Support : Capability : Veterinary|S-G-USMVT-|
|Sustainment : Ordnance : Corps Support|S-G-USXOC-|
|Sustainment : Ordnance|S-G-USXO--|
|Sustainment : Ordnance : Theater/Echelons Above Corps Support|S-G-USXOT-|
|Sustainment : Quartermaster : Corps Support|S-G-USAQC-|
|Sustainment : Quartermaster|S-G-USAQ--|
|Sustainment : Quartermaster : Theater/Echelons Above Corps Support|S-G-USAQT-|
|Sustainment : Transportation : Capability : Missile|S-G-USTI--|
|Sustainment : Transportation : Corps Support : Capability : Missile|S-G-USTIC-|
|Sustainment : Transportation : Theater/Echelons Above Corps Support : Capability : Missile|S-G-USTIT-|
|Sustainment : US Supply Class II : Corps Support|S-G-USS2C-|
|Sustainment : US Supply Class II|S-G-USS2--|
|Sustainment : US Supply Class II : Theater/Echelons Above Corps Support|S-G-USS2T-|
|Sustainment : US Supply Class III : Aviation : Corps|S-G-USS3AC|
|Sustainment : US Supply Class III : Aviation : Theater|S-G-USS3AT|
|Sustainment : US Supply Class III : Capability : Aviation|S-G-USS3A-|
|Sustainment : Water : Corps Support|S-G-USSWC-|
|Sustainment : Water|S-G-USSW--|
|Sustainment : Water : Theater/Echelons Above Corps Support|S-G-USSWT-|
|Sustainment : Water Purification : Corps Support|S-G-USSWPC|
|Sustainment : Water Purification|S-G-USSWP-|
|Sustainment : Water Purification : Theater/Echelons Above Corps Support|S-G-USSWPT|
|Vehicle : Armored Vehicle : Armored Fighting Vehicle C2|S-G-EVAC--|
|Weapon (Air) : Decoy|S-A-WD----|
|Weapon (Air)|S-A-W-----|
|Weapon/Weapon System : Air Defense Missile Launcher|S-G-EWMA--|
|Weapon/Weapon System : Air Defense Missile Launcher : Theater|S-G-EWMAT-|
|Weapon/Weapon System : Air Defense Missile Launcher : Theater : TELAR|S-G-EWMATE|
|Weapon/Weapon System : Air Defense Missile Launcher : Theater : TLAR|S-G-EWMATR|
|Weapon/Weapon System : Direct Fire Gun : Self Propelled : Heavy|S-G-EWDHS-|
|Weapon/Weapon System : Direct Fire Gun : Self Propelled : Light|S-G-EWDLS-|
|Weapon/Weapon System : Direct Fire Gun : Self Propelled : Medium|S-G-EWDMS-|
|Weapon/Weapon System : Howitzer : Self Propelled : Heavy|S-G-EWHHS-|
|Weapon/Weapon System : Howitzer : Self Propelled : Light|S-G-EWHLS-|
|Weapon/Weapon System : Howitzer : Self Propelled : Medium|S-G-EWHMS-|
|Protection Areas : Biologically Contaminated Area |G-M-NB----|
|Protection Areas : Chemically Contaminated Area |G-M-NC----|
|Protection Areas : Radioactive Area |G-M-NR----|

@csmoore fyi

**Comment by csmoore** [comment]
Here is a specific example/screenshot just to clarify this issue for retest:

Repro Steps:

1. Search Tab: Search "Scout"
2. Choose Movement and Manuver : Recon/Cavalry/Scout
3. Click Symbol Tab (or Hit Next)
4. Change the Function Name to : Movement and Manuver : Recon/Cavalry/Scout : Pack Animal
5. Click Add to Map
6. Image Preview and Map symbols should match

![mse-icondiff](https://cloud.githubusercontent.com/assets/3090809/21199949/8b24ca40-c213-11e6-9f8b-d8050894881b.JPG)

![mse-icondiff2](https://cloud.githubusercontent.com/assets/3090809/21199953/904be51c-c213-11e6-8317-8117871a7b43.JPG)

**Comment by csmoore** [comment]
Should be ready to verify in next build.

See simpler repro steps at https://github.com/Esri/military-symbol-editor-addin-wpf/issues/110#issuecomment-267151702

**Comment by Dbarnes1** [comment]
@csmoore great work! Verified: 

![image](https://cloud.githubusercontent.com/assets/13024357/21360114/779abf6e-c693-11e6-9a0c-4c2db9948144.png)
