### ISSUE TITLE
Poor tooltip name and description for Military Symbol Editor addin Tooltip (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/military-symbol-editor-addin-wpf#118]
When I hover over the Visibility addin the following tooltip is displayed:
![image](https://cloud.githubusercontent.com/assets/4635490/21275300/fcd73f38-c380-11e6-8960-ff2aa4b01a50.png)

"Show Dockpane" - there is no reason to use the verb "Show". Users know that the tool will open or do something. It needs to state the name of the addin.

"Show Dockpane" - This doesn't help the user at all. We should be describing what the user can do with the addin. Look at other tools and see how they describe the tool.

**Comment by csmoore** [comment]
Good catch - unless there are other suggestions we can change the tooltip to:

Line1: "Military Symbol Editor"
Line2: "Open the Military Symbol Editor"

**Comment by csmoore** [comment]
Ready to verify in next build

**Comment by elinz** [comment]
@csmoore I'll provide you with a better description. We should be describing what the tool does; not describing what happens when you click the addin button.

**Comment by elinz** [comment]
@csmoore Here's what we should use for the tooltip description....
![image](https://cloud.githubusercontent.com/assets/4635490/21359604/a1e4b1f0-c691-11e6-937d-dee21c958b47.png)
Thanks.

**Comment by csmoore** [comment]
Updated in #122 - looks like this now:

![image](https://cloud.githubusercontent.com/assets/3090809/21362368/1896de4e-c6b6-11e6-878d-78c68b1034fa.png)

**Comment by elinz** [comment]
@csmoore @kgonzago Validated that the tooltip name and description in the individual military symbol editor addin is good, i.e. matches screenshot above. Closing this issue. This is the tooltip name and description that should be used for this tool in the single Military Tools for ArcGIS add-in.
