### ISSUE TITLE
Dark theme removes visibility of some settings

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/military-symbol-editor-addin-wpf#124]
ArcGIS Pro 1.4 will come with the "Dark Theme" option, which is messing with many of our UI components across military tools. This is within the symbol editor setting for switching between 2525D and 2525B Change 2.

![image](https://cloud.githubusercontent.com/assets/13024357/21625755/07281f9e-d1c2-11e6-8b7b-ccddf3b383ed.png)

**Comment by joebayles** [comment]
It is also affecting the tags.

![image](https://cloud.githubusercontent.com/assets/5016557/21872810/8670531c-d81f-11e6-84b1-ac176ea3464a.png)

**Comment by joebayles** [comment]
Verified that the radial buttons work. Will open a new, lower-priority issue for other changes.
