### ISSUE TITLE
Add to Map Button no longer working

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/military-symbol-editor-addin-wpf#125]
In the updated version (1/4 build) of the Military Symbol Editor, the "Add to Map" button has stopped working. I can open the add-in, search for a symbol and add the schema to the project, but when i try and click add to map, the map point tool doesn't turn on. The button is highlighted but nothing else happens:
![image](https://cloud.githubusercontent.com/assets/13024357/21661232/fa391466-d287-11e6-88bb-c4b975a31ccc.png)

@elinz was also able to reproduce. 

@csmoore fyi.

**Comment by csmoore** [comment]
I do see this issue in the **single Military Tools For ArcGIS addin** - not sure why the Symbol Editor custom tools aren't available now in this combined addin (I do see them in the combined DAML), investigating...

**Comment by csmoore** [comment]
Looks like just a typo in the tool classname, should be ready to test in next build.

**Comment by Dbarnes1** [comment]
Fixed, closing.

Thanks @csmoore !
