### ISSUE TITLE
Select button on Military Symbol Editor Modify pane doesn't work until core select button is used.

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/military-symbol-editor-addin-wpf#126]
in fixing some of the other selection issues, I think that the select tool in the modify pane broke. The main issue here is that the select tool can be highlighted when you click on it but won't work when you move your cursor over the map. I can get this button to work, but only after using the core selection tool. 

I'm using the (1/4) version of the add-in with pro 1.4.7195

**Comment by csmoore** [comment]
I do see this issue in the **single Military Tools For ArcGIS addin** - not sure why the Symbol Editor custom tools aren't available now in this combined addin (I do see them in the combined DAML), investigating...

Related to/same issue as #125

**Comment by csmoore** [comment]
Looks like just a typo in the tool classname, should be ready to test in next build.

**Comment by Dbarnes1** [comment]
Fixed, closing.
