### ISSUE TITLE
Run XAML Styler on files

### ISSUE THREAD

**Issue by csmoore** [Esri/military-symbol-editor-addin-wpf#130]
After this release, we should run the [XAMLStyler](https://marketplace.visualstudio.com/items?itemName=NicoVermeir.XAMLStyler) @jmccausland suggested and clean up the commented out XAML code.

Waiting until after release because it changes the entire XAML file and we lose the change history. This issue is just a reminder so we don't forget.

**Comment by jmccausland** [comment]
When you install the XAML styler it has an option "Misc -> Beautify on saving XAML" that is set to True by default.  I have this set to False and manually apply.

**Comment by csmoore** [comment]
Done/merged in #150
