### ISSUE TITLE
Dark theme visibility issues

### ISSUE THREAD

**Issue by joebayles** [Esri/military-symbol-editor-addin-wpf#133]
While the previous issue was a showstopper, I am assuming these are for V.1.1.

Several symbols are very hard to see in the preview window and the lists because they are black on black. For example, Rally Point.
![image](https://cloud.githubusercontent.com/assets/5016557/21903227/ec266cf2-d8b3-11e6-8a58-0ed65cfb8938.png)
![image](https://cloud.githubusercontent.com/assets/5016557/21903230/ef1e58de-d8b3-11e6-8d66-5fee42441fe6.png)

Tags are tough to read with white text on light blue tags.

Also, the buttons at the bottom are still kludgy, since they are obviously for a light theme, but not. And they don't respect each other's boundaries:
![image](https://cloud.githubusercontent.com/assets/5016557/21903325/46cda21a-d8b4-11e6-84a0-157b4bb1e30c.png)

**Comment by csmoore** [comment]
The issues with the images and the back buttons seems to have been addressed in the SDK, I did need to make some brush changes in the tags. Here is how things should look after next PR : 

![image](https://cloud.githubusercontent.com/assets/3090809/26414776/33533bc8-407e-11e7-8b80-143a659731cb.png)

**Comment by dfoll** [comment]
closing out this issue and creating issues that are tab specific, to try to catch all remaining visibility issues with MSE dark theme

**Comment by dfoll** [comment]
#162 #163 #164 #165 #166 #167
