### ISSUE TITLE
Version number and hyperlinks to external website in "About" dialog?

### ISSUE THREAD

**Issue by elinz** [Esri/military-symbol-editor-addin-wpf#134]
The "About" dialog contains the version number 1.2.0. Should this be in sync with the version number of the addin? Maybe we shouldn't display a version number on the About dialog. We don't have an About dialog in any other tool. Is this dialog really necessary?

Also the "About" dialog has links to external http://solutions.arcgis.com/defense/help/military-overlay/ and http://solutions.arcgis.com/defense/help/military-overlay-information-model/. Should the "About" dialog contain links to external sites that won't be reachable to many of our customers?

![image](https://cloud.githubusercontent.com/assets/4635490/22074283/b4b76cbe-dd5c-11e6-8488-5fd6f648b061.png)

**Comment by nfeuerstein** [comment]
Remove version number from the "about" and remove external links.

**Comment by csmoore** [comment]
Requested changes made in #135 - will be available in next build after merge.

Form should look like this now:

![image](https://cloud.githubusercontent.com/assets/3090809/22077534/898127a8-dd82-11e6-8b5f-ec9b150f5fa7.png)

**Comment by elinz** [comment]
Verified in build 1140 (18 Jan 2017 12:25) that the About dialog no longer has version number and hyperlinks to external web pages. Closing issue.
