### ISSUE TITLE
Make Corrections to Install Military Symbol Editor topic from Pro Doc

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/military-symbol-editor-addin-wpf#136]
![image](https://cloud.githubusercontent.com/assets/13024357/22162764/c41245ae-df04-11e6-9c88-b39f2b97f343.png)

We removed this install topic for the other parts of military tools, so I'm going to go ahead and remove this for consistency sake.

**Comment by Dbarnes1** [comment]
removed from map- setting to verify.

**Comment by csmoore** [comment]
So long as the "Settings" step (Step 3) is somewhere. 

You might want to want to also call the settings button a "hyperlink" ( @dhagens said he had a hard time finding since he was looking for a button )

**Comment by Dbarnes1** [comment]
@csmoore good point. Instead of removing the topic alltogether, I'll edit the inaccurate parts of the topic.
