### ISSUE TITLE
Add Favorite Button Appears Grayed Out

### ISSUE THREAD

**Issue by csmoore** [Esri/military-symbol-editor-addin-wpf#147]
The button styles differ between the "Add to Map" and "Add Favorite" buttons making the "Add Favorite" button appear grayed-out/disabled (it is not)

This style change should/might be fixed/addressed with https://github.com/Esri/military-tools-desktop-addins/issues/2

![image](https://cloud.githubusercontent.com/assets/3090809/22786882/423fb4ea-eea8-11e6-83c1-a8407369a67a.png)

**Comment by NatalieCampos** [comment]
This has been verified and can be close
