### ISSUE TITLE
Documentation for MSE Add-In assumes the user already has an environment set that they are ready to start working

### ISSUE THREAD

**Issue by dfoll** [Esri/military-symbol-editor-addin-wpf#149]
Documentation for MSE Add-In assumes the user already has an environment set that they are ready to start working, ie has appropriate layers available and ready to use. Should we include instructions or some reference to get them set up?

**Comment by csmoore** [comment]
I believe it is (or was) there, but it is somewhat buried in the step where you actually select a symbol:

![image](https://cloud.githubusercontent.com/assets/3090809/22910817/91d11e2e-f22a-11e6-9945-28ad93a833d4.png)

**Comment by BobBooth** [comment]
I'd second CMoore on that - the add-in is designed to detect when the map doesn't have data with the correct schema, and makes it easy to add.

**Comment by dfoll** [comment]
i as well agree with @csmoore. we should fix the documentation to make this more obvious

**Comment by Dbarnes1** [comment]
https://github.com/Esri/military-symbol-editor-addin-wpf/issues/154 I think that if we changed how the symbol editor operates, we can improve the add-in and adjust the documentation as needed.

**Comment by dfoll** [comment]
this is not an issue until enhancement #154 is implemented, so i'm closing this. i placed the appropriate affects doc tag on #154
