### ISSUE TITLE
Issues when editing features other than military symbology

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbol-editor-addin-wpf#152]
When you have configured Military Tools and you start using the Symbol Editor you constantly get an alert that this is not a military symbol. 

![image](https://cloud.githubusercontent.com/assets/5488313/23233001/421c7002-f902-11e6-8063-dc78a9412b7b.png)

**Comment by csmoore** [comment]
Can you provide some more repro info (and maybe screenshot that includes map+addin) like is this with a particular template/dataset? Is there something selected on the map that is not a military symbol when the editor modify tab is active? Dataset with both standards in the project?

(Unless bug) you should only get this message if (1) you are on the selection/modify tab and (2) you select a non-military feature.

**Comment by topowright** [comment]
Here are the steps to replicate the issue: 

1. Start ArcGIS Pro
2. Create a New Project
3. Insert New Map
4. Click on the Military Symbol Editor from the Military Tools Add-in
5. Add the schema for either of the associated standards
6. Add Dark Map notes by clicking he add button on the  the Insert Ribbon
7. From the Edit Ribbon click Create Features
8. From the Create Features pane attempt to add a non military feature from the Dark Map Notes and you will get the error

**Comment by Dbarnes1** [comment]
@csmoore I think what could be done here to resolve this issue is for the symbol editor to somehow ignore all features that are using a renderer other than the dictionary renderer. Is that possible in the SDK?

**Comment by csmoore** [comment]
@Dbarnes1 That's a great idea (and was even a [TODO](https://github.com/Esri/military-symbol-editor-addin-wpf/blob/dev/source/ProSymbolEditor/ViewModels/MilitarySymbolDockpaneViewModel.cs#L1689) but probably should have done that to begin with )

**Comment by Dbarnes1** [comment]
@csmoore glad we're thinking similarly. Lets advocate for this enhancement to be made at planning tomorrow.

**Comment by topowright** [comment]
I do not categorize this as an enhancement. I am adding the bug tag based on the user experince. I find it very challenging to do any other type of work that involves editing if I get this popup every time I edit a feature. @nfeuerstein @lfunkhouser

**Comment by csmoore** [comment]
Removed this pop-up in #155 - this was actually a bug, this pop-up was only supposed to happen once per session, but sounds like the warning could be removed altogether

**Comment by topowright** [comment]
@csmoore great work!
I have verified that this bug is fixed. Here is a screen shot that shows what I have been able to add: 

![image](https://cloud.githubusercontent.com/assets/5488313/26513671/9db3c434-4221-11e7-99eb-de5fc4c1d566.png)
