### ISSUE TITLE
Search tab Dark theme visibility

### ISSUE THREAD

**Issue by dfoll** [Esri/military-symbol-editor-addin-wpf#162]
- [x] the search box where you enter the symbol you want to search for is still showing as white this box should be a dark background with white text, like other dark theme search boxes
![image](https://cloud.githubusercontent.com/assets/5322669/26514801/2f9d166e-4229-11e7-8551-e2fe7142770d.png)
(currently)
![image](https://cloud.githubusercontent.com/assets/5322669/26514806/39e5483a-4229-11e7-9591-c67d8657e19e.png)
(should look like this)

- [x] Add to Map button is white, should be dark like the other buttons
![image](https://cloud.githubusercontent.com/assets/5322669/26514873/e02e5fec-4229-11e7-98b7-94caf4073773.png)
(Add Favorite and Add to Map should match)

**Comment by NatalieCampos** [comment]
This is what the button looks like in Pro 2.0

![image](https://user-images.githubusercontent.com/5116835/27243088-20d19e8a-5295-11e7-8568-67faa639cb08.png)

**Comment by topowright** [comment]
@csmoore has started to work on the toggle buttons. 
- [ ] Application should be tested from Jenkins
- [ ] Product should build at 2.1

**Comment by topowright** [comment]
- [ ] Create the end solution as it is given to customers
- [ ] Add the widget components
- [ ] Add the GP components
- [ ] Add ArcGIS Pro Solution
- [ ] Add ArcMap Solution
- [ ] Add the documentation

**Comment by topowright** [comment]
I was able to complete the zip file creation, building the Military Tools Solution and copying the zip file to the testing location.

**Comment by csmoore** [comment]
When you want to build to test this issues - you can set Jenkins to build from this branch:
https://github.com/Esri/military-symbol-editor-addin-wpf/tree/csm/dark-theme-issues

This issue should be ready to verify once built:

![image](https://user-images.githubusercontent.com/3090809/34157083-058d4b52-e48e-11e7-8696-1ac5e0a3fe8a.png)

**Comment by topowright** [comment]
I have been able to finish building Military Tools For ArcGIS against ArcGIS Pro 2.1.

**Comment by topowright** [comment]
I have been able to finish building Military Tools For ArcGIS against ArcGIS Pro 2.1. 

The build location: 
Solutions\DefenseSolutions\MilitaryToolsForArcGIS\3.0\

**Comment by topowright** [comment]
Added a step in the checklist to check dark theme on each tab.
