### ISSUE TITLE
Favorites tab Dark theme visibility

### ISSUE THREAD

**Issue by dfoll** [Esri/military-symbol-editor-addin-wpf#164]
- [x] Symbol Attributes window is white, it should be dark like the regular attributes window
![image](https://cloud.githubusercontent.com/assets/5322669/26515190/2616981e-422d-11e7-8a5c-47f0c1116478.png)
(currently)
![image](https://cloud.githubusercontent.com/assets/5322669/26515194/2d34e98e-422d-11e7-8634-b43f0ef7492b.png)
(should look like this)

- [x] Add to Map button is white, it should be dark like the other dark theme buttons
![image](https://cloud.githubusercontent.com/assets/5322669/26515206/4b6d8578-422d-11e7-9a20-12918d1d12c1.png)
(currently)
![image](https://cloud.githubusercontent.com/assets/5322669/26515208/59a03136-422d-11e7-8541-a38166bf147d.png)
(should have this style)

**Comment by csmoore** [comment]
Addressed in #206, #207 

![image](https://user-images.githubusercontent.com/3090809/34233436-602bcf9a-e5b3-11e7-82fa-749ae8cf3660.png)
