### ISSUE TITLE
Symbol tab Dark theme visibility

### ISSUE THREAD

**Issue by dfoll** [Esri/military-symbol-editor-addin-wpf#165]
- [x] text boxes are while color they should be dark boxes with white text
![image](https://cloud.githubusercontent.com/assets/5322669/26515248/b9b4003e-422d-11e7-9c49-d15e9615086e.png)
(currently)
![image](https://cloud.githubusercontent.com/assets/5322669/26515255/d30b49fc-422d-11e7-87a4-68806598c30d.png)
(should be this style)

- [x] Symbol Attributes window is white, should match dark theme of regular attributes window
![image](https://cloud.githubusercontent.com/assets/5322669/26515270/f2962706-422d-11e7-833a-fb37e259d641.png)
![image](https://cloud.githubusercontent.com/assets/5322669/26515275/fa0cefb0-422d-11e7-956c-039bc3c9a450.png)
(should be this style)

- [x] Add to Map button is white, should match dark theme buttons
![image](https://cloud.githubusercontent.com/assets/5322669/26515280/10c39a7e-422e-11e7-9606-15d2a50e1525.png)
(currently)
![image](https://cloud.githubusercontent.com/assets/5322669/26515283/19b45d30-422e-11e7-8c30-9303e3738579.png)
(should match this style)

**Comment by csmoore** [comment]
Addressed in #206, #207 

![image](https://user-images.githubusercontent.com/3090809/34233387-18b76246-e5b3-11e7-8ed7-17f1057a0de9.png)

**Comment by topowright** [comment]
PR #207 has fixed this issue
