### ISSUE TITLE
Enter Coordinates tab Dark theme visibility

### ISSUE THREAD

**Issue by dfoll** [Esri/military-symbol-editor-addin-wpf#167]
- [ ] Symbol Attributes table is white, it should match the regular dark theme Attributes table
![image](https://cloud.githubusercontent.com/assets/5322669/26515384/28435256-422f-11e7-818d-11a2f4241f38.png)
(currently)
![image](https://cloud.githubusercontent.com/assets/5322669/26515386/2f52ff74-422f-11e7-8c6a-ee91a815c92b.png)
(should match the style of the dark theme Attributes table)

- [ ] Add to Map button is white, it should match other dark theme buttons
![image](https://cloud.githubusercontent.com/assets/5322669/26515402/548281ac-422f-11e7-9fd7-cc62fd51133e.png)
(Add to Map button should match the "Add Favorite" button

**Comment by csmoore** [comment]
Addressed in #207

**Comment by topowright** [comment]
PR #207 has fixed this issue
