### ISSUE TITLE
 Save Image or Copy to Clipboard Image Flipped

### ISSUE THREAD

**Issue by csmoore** [Esri/military-symbol-editor-addin-wpf#168]
Issue:

 Save Image or Copy to Clipboard Image from Symbol Preview is Flipped

Steps:
1. Search for a symbol and set it properties
2. Right click on the Preview Image and select Save Image As... or Copy to Clipboard
3. Resulting symbol image is flipped 

Screenshot:
![image](https://cloud.githubusercontent.com/assets/3090809/26679690/3a691b68-46a4-11e7-84b3-c9767ddfe57b.png)

Discussion:
This is happening as a result of a workaround we did to get SymbolStyleItem.PreviewImage to export at a size > 64 pixels (see [comments/discussion](https://github.com/Esri/military-symbol-editor-addin-wpf/blob/dev/source/ProSymbolEditor/Models/SymbolAttributes/SymbolAttributeSet.cs#L188) ). To solve this we would need to (1) see if fixed in Pro 2.0 or (2) flip the image ourselves on export 

Workaround:
Use an image editor to rotate/flip the image until this issue is resolved

**Comment by NatalieCampos** [comment]
As of this morning, I do not see the saved as .png file being flipped.  @csmoore has this been fixed?  Shall i close it?

![image](https://user-images.githubusercontent.com/5116835/27144649-936468e2-50e7-11e7-9172-22c86751adcb.png)

**Comment by NatalieCampos** [comment]
This issue has been verifed.
