### ISSUE TITLE
using features from favorites pane does not add the military information model

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/military-symbol-editor-addin-wpf#176]
When using favorites that have been previously created and trying  to add a favorite to the map, the military information model is not added to the map.  This means you have to search for a symbol add it to the map to generate the add military information model.  To reproduce problem:

1. After creating favorites in a pro project, close the project.
2. Create a new project and attempt to add features from the favorites pane to the  map.  
3. you will reivce the following warning

![image](https://user-images.githubusercontent.com/5116835/27155450-ea213806-510d-11e7-9557-09289fe0b516.png)

4. To add the military information model, you must search for a symbol and attempt to add it. 

___

(added)
**Full repro steps with desired outcome:**

1. Start Pro
1. Create a new Map Project
1. Launch Military Symbol Editor
1. Ensure Standard set to 2525D (on bottom right, click settings if not)
1. Go to Favorites Tab
1. Click Import 
1.  Import SampleFavorites.json.txt file attached to this issue (remove .txt extension and keep just .json)
1. Click on Favorite
1. Click on Pro Map if not visibile
1. Click on Add to Map Button
1. Add-In Disabled Form should prompt you to add the Military Overlay Schema 
1. After Military Overlay Schema is added you should be able to add symbol to the map

[SampleFavorites.json.txt](https://github.com/Esri/military-symbol-editor-addin-wpf/files/1907964/SampleFavorites.json.txt)

**Comment by lfunkhouser** [comment]
Removing Milestone Version-Next for@nfeuerstein review to prioritize.

**Comment by csmoore** [comment]
This is confusing - if you start at the favorites tab (rather than the search) on a new map than it does not add the required layer packages and you can't proceed. 

![image](https://user-images.githubusercontent.com/3090809/31078687-17eb54bc-a751-11e7-86c1-63c00ae9f00f.png)

Changing this from enhancement to bug

**Comment by topowright** [comment]
@csmoore I understand how this might be an issue if I already had favorites from another instance in my add-in and I just wanted to start using the MSE. 
What is the least past of resistance: 
1.Have a prompt that tells the users to add the symbols by searching for a symbol on the search tabs? 
          I think this is sub optimal based on the fact that I already know the symbol I want to add, which is 
          located in my favorites. 

2.Add the missing schema to the map when the user tries to add the feature from favorites.

**Comment by topowright** [comment]
After messing with this more I think the same functionality that we check when a user selects a feature from the search results menu should be implemented in the **Add to Map** button. Then it will fix the problem no matter what tab you are on.  If we have to do a check each time the button is used maybe we can store a active variable somewhere that would allow the button to do that check faster.

**Comment by csmoore** [comment]
Looking at this now

**Comment by csmoore** [comment]
Addressed in PR #227 

Repro steps updated

**Comment by ACueva** [comment]
I can get this same error message to be thrown again.

Steps to reproduce:
1. Import the favorites from the file listed above.
2. Select a symbol
3. Click "Add to Map"
4. When prompted to add the Military Overlay Layer Package schema to the map, select "No"
![2018-06-14_15-35-38](https://user-images.githubusercontent.com/3093940/41441755-d964ebe8-6fe8-11e8-83d4-c44969f45e8f.jpg)
5. Click on the map, the following error will be thrown:
![2018-06-14_15-33-10](https://user-images.githubusercontent.com/3093940/41441677-7fc3df9a-6fe8-11e8-9735-f7c2e2696f44.jpg)

**Comment by topowright** [comment]
closing this issue with the issue broken into two parts: 
issue #241 and #242
