### ISSUE TITLE
Coordinates tab dark theme button text not visible

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/military-symbol-editor-addin-wpf#177]
On the Coordinates tab the text on the two button below are not visible. One is the Add Coordinates to Map button and the Other is the Mark/Pan to Coordinates.  

![image](https://user-images.githubusercontent.com/5116835/27194902-46be553e-51b9-11e7-8d7d-7b6f611c3274.png)

**Comment by csmoore** [comment]
@NatalieCampos this is the expected (the "disabled") appearance until you enter in a valid coordinate and then the buttons appear enabled:

![image](https://user-images.githubusercontent.com/3090809/27202538-0159f2be-51f0-11e7-8b6b-8e8598418e4d.png)

**Comment by NatalieCampos** [comment]
since this is expected behavior closing this as a non-issue
