### ISSUE TITLE
black symbology not visible in dark theme

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/military-symbol-editor-addin-wpf#181]
The symbols that are black are very hard to see against the already black back ground.  See graphic below

![image](https://user-images.githubusercontent.com/5116835/27243732-236b5b1a-5298-11e7-9fa5-801d2a25638a.png)

Compare to more colorful symbols

![image](https://user-images.githubusercontent.com/5116835/27243752-3cc7d0de-5298-11e7-92cb-94fff9e0d161.png)

**Comment by topowright** [comment]
This issue will be closed as designed. We do not want to create a new background for just this tool when looking at symbology in the dark theme. We do not want to alter the way we are reading the standard for military symbology.
