### ISSUE TITLE
Update the Modify tab for Dark Theme

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbol-editor-addin-wpf#188]
Currently the table that is used to understand more about a symbol that is selected does not support dark theme. 

![image](https://user-images.githubusercontent.com/5488313/27416531-df609604-56c2-11e7-8e45-cece4a644f80.png)

**Comment by csmoore** [comment]
That table uses a 3rd controls (Exceed WPF Toolkit) that doesn't support themes in the free version so we would need to remove this/use something else.

**Comment by csmoore** [comment]
Note: this is a repeat of #163

**Comment by topowright** [comment]
PR #207 has fixed this issue
