### ISSUE TITLE
Codes for Domain "Reinforced" are showing instead of the description - update LPKXs after fixed there

### ISSUE THREAD

**Issue by dfoll** [Esri/military-symbol-editor-addin-wpf#189]
Codes for Domain "Reinforced" are showing the instead of the description. This is happening with 2525D and 2525Bc2.

When I create a symbol and assign a value for the reinforced field via the label tab in MSE I expect to see a "+", "-", or "+/-" displayed, instead I see "0", "1", or "2" displayed.

![image](https://user-images.githubusercontent.com/5322669/27437527-64648cc6-5717-11e7-98bf-59b0b92f986d.png)
![image](https://user-images.githubusercontent.com/5322669/27437542-6c6e5ce4-5717-11e7-93e5-550a2790a0ad.png)

This will require:

- [x] Updating/fixing the domains in the LPKXs (in the [Military Overlay Info Model](http://esriurl.com/MilitaryOverlayInformationModel) ) - see: https://github.com/Esri/military-features-data/issues/244
- [ ] Taking those updates and updating the [LPKXs](https://github.com/Esri/military-symbol-editor-addin-wpf/tree/dev/source/ProSymbolEditor/LayerFiles) deployed with this addin

**Comment by dfoll** [comment]
@lfunkhouser @nfeuerstein since fixes are still happening, wanted to confirm you guys want this listed as a known issue for 2.0

**Comment by joebayles** [comment]
If this is **After Next**, it _has_ to be a known issue. This is pretty commonly used.

FYI @dfoll @lfunkhouser @nfeuerstein

**Comment by nfeuerstein** [comment]
Yes on known issue.

**Comment by csmoore** [comment]
It would need fixed here: https://github.com/Esri/military-features-data/issues/244 - this one is probably a  duplicate & can be closed

**Comment by csmoore** [comment]
This is a repeat of https://github.com/Esri/military-features-data/issues/244 - but the gdb/schema layer packages/lpks deployed with this addin will need updated in this repo so we should keep this issue open as a reminder (updated title and description)

**Comment by csmoore** [comment]
Addressed in #203 - should look like this now:

![image](https://user-images.githubusercontent.com/3090809/33388936-5d70d922-d4ff-11e7-96d0-d9bb02de53fd.png)

**Comment by topowright** [comment]
@csmoore have we given these new updates to the Pro team to be integrated into ArcGIS Pro 2.1?

**Comment by csmoore** [comment]
@topowright - these files (the GDB and lpkx) are only included in the Military Overlay (and Symbol Editor) downloads

**Comment by csmoore** [comment]
I just got the dreaded "Spatial Index Invalid" error with these LPKs (which was resolved in Pro some time ago but seems like it is back) -so we'll probably have to re-introduce the workaround (to call the GP tool "Remove Spatial Index") and re-do these lpkxs/this PR. 

![image](https://user-images.githubusercontent.com/3090809/34227574-a329422c-e59b-11e7-9053-98e4c095f8a0.png)

**Comment by topowright** [comment]
This has been fixed in PR #203.

**Comment by csmoore** [comment]
PR #203 accidentally introduced a problem [noted above](https://github.com/Esri/military-symbol-editor-addin-wpf/issues/189#issuecomment-353177197) so I need to redo these LPKXs and do new PR

**Comment by topowright** [comment]
@csmoore good catch. I read the top comments and I must have missed your comment that was made yesterday.

**Comment by csmoore** [comment]
Spatial index error addressed in PR #208 - should be ready for verify/QC

**Comment by topowright** [comment]
This has been verified in the latest build of Military Tools for ArcGIS
