### ISSUE TITLE
Clean up/delete feature branches

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-symbol-editor-addin-wpf#194]
Delete the feature branches that were merged into the code or are no longer relevant. If the branch is still active, please update the name of the branch using the feature branch naming convention,  `<initials>/<issue#>-<short description>` .
- [ ] ArcGIS_Pro_1.2
- [x] csm/dark-icons
- [x] csm/favorite-to-feature-template2.0
- [x] csm/favorite-to-template
- [x] csm/update-to-prosdk2.0
- [x] csm/#168-flipped-export-image
- [x] lw-jenkinsPro2.0-test
- [x] pro-sdk-2.0
- [ ] v2.0
- [ ] v2.1

**Comment by csmoore** [comment]
Deleted the ones I could - this branch is locked so requires repo Admin rights to delete:

ArcGIS_Pro_1.2 

These are the version/release maintenance branches created as part of the release process so should remain:
v2.0
v2.1

**Comment by lfunkhouser** [comment]
Verified. Closing.
