### ISSUE TITLE
Save Project when datamodel added to the map

### ISSUE THREAD

**Issue by csmoore** [Esri/military-symbol-editor-addin-wpf#195]
When the datamodel/layer package is added to the project/map for the first time it should also save the project (automatically or by prompting the user).

If the user forgets to save the project manually the datamodel layers will be lost in the map contents and the next time the project is opened, the error below is given when trying to use the addin:

![image](https://user-images.githubusercontent.com/3090809/31079210-d1d58af4-a752-11e7-9b74-7d139f0bf248.png)

Repro Steps:

1. Create new Pro Map project
2. Open Military Symbol Editor Addin 
3. Search for a symbol
4. Click on symbol
5. Click yes when prompted to add datamodel to project
6. --> Project should automatically save at this point
7. Close the Pro project without saving (click No if prompted to save)
8. Reopen the same Pro project created in step `1` 
9. Military Overlay layers should be present

**Comment by csmoore** [comment]
Looking at this issue now - should be a simple fix as long as there aren't any CIM/UI threading issues

**Comment by csmoore** [comment]
Addressed in PR #224 - saves after lpkx added now

**Comment by topowright** [comment]
Verified this on ArcGIS Pro 2.2 on the MT build 18 and the single build as well. This is fixed and works for both 2525B and 2525D
