### ISSUE TITLE
Static Code Analyzer : Null Dereference

### ISSUE THREAD

**Issue by jmccausland** [Esri/military-symbol-editor-addin-wpf#197]
the SCA report shows there are possible Null Dereference issues in the code.

Most of the flagged code is due to query interfaces via the 'as' keyword.  When it is safe to do a direct cast to an Esri API Interface, we should do that.  Everywhere else, null check and refactor if needed.

The ReSharper tool can assist with this exercise and minimize these issues in the future.

- when safe, change to direct cast
- add null checks and refactor where needed

**Comment by lfunkhouser** [comment]
Closing. This work was done and included in the code optimization of MSE for the June 2018 release.
