### ISSUE TITLE
Static Code Analyzer : Empty Catch Block

### ISSUE THREAD

**Issue by jmccausland** [Esri/military-symbol-editor-addin-wpf#199]
- remove try/catch or comment if needed but does nothing

**Comment by csmoore** [comment]
This has been addressed - except in ProSymbolUtilities.GetCoordinateType where this behavior (trying a coordinate and catching the exception if it can't be parsed ) is by design

**Comment by csmoore** [comment]
Addressed in PR #220 

Moving to done and will get reviewed/QA/QC with SCA Issue #197
