### ISSUE TITLE
Static Code Analyzer : Logging Practice with use of system output stream

### ISSUE THREAD

**Issue by jmccausland** [Esri/military-symbol-editor-addin-wpf#200]
- remove outputs or wrap with 
```#if DEBUG ```
```#endif```

**Comment by csmoore** [comment]
This has been addressed in branch https://github.com/Esri/military-symbol-editor-addin-wpf/tree/csm/%23197-null-dref-and-sca-issues

**Comment by csmoore** [comment]
Addressed in PR #220 

Moving to done and will get reviewed/QA/QC with SCA Issue #197
