### ISSUE TITLE
Can't clear/null/disable Date/Time label attributes (it is Mandatory for Symbols) 

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/military-symbol-editor-addin-wpf#22]
It doesn't let me draw symbols with a blank date/time field. the boxes come up as red: 
![image](https://cloud.githubusercontent.com/assets/13024357/14365014/56ca740c-fcc0-11e5-8062-f7a363c528a3.png)

Does every symbol need to be time stamped like this? @csmoore @tlauver

**Comment by csmoore** [comment]
With some effort (deleting each DTG character individually) this is now nullable but @tlauver is going to check if he can make null the default to make this easier on the user

**Comment by BobBooth** [comment]
It would be nice if you had a choice - in some cases it makes sense to set it to null by default, but in others it might be more useful to set it to the current datetime.

**Comment by csmoore** [comment]
Verified in #69
