### ISSUE TITLE
Military Symbol Editor fails to compile after Coordinate Conversion changes

### ISSUE THREAD

**Issue by ACueva** [Esri/military-symbol-editor-addin-wpf#228]
### Environment:
Dev branches from GitHub
Compiling on Pro 2.1 Final 
Visual Studio 2015 Update 3

The changes here:
https://github.com/Esri/coordinate-conversion-addin-dotnet/commit/e44bd192a7892853b547679e42cad678d81ecdd7

have caused our Military Tools and Military Symbol Editor builds to fail as shown here:

```
  Utilities\ProSymbolUtilities.cs(94,30): error CS7036: There is no argument given that corresponds to the required formal parameter 'coord' of 'CoordinateDD.TryParse(string, bool, out CoordinateDD)' [C:\Jenkins\workspace\MT\3.0\ArcGIS Pro 2.1\military-symbol-editor-addin-wpf\source\ProSymbolEditor\u4cgkarx.tmp_proj]
  Utilities\ProSymbolUtilities.cs(106,31): error CS7036: There is no argument given that corresponds to the required formal parameter 'ddm' of 'CoordinateDDM.TryParse(string, bool, out CoordinateDDM)' [C:\Jenkins\workspace\MT\3.0\ArcGIS Pro 2.1\military-symbol-editor-addin-wpf\source\ProSymbolEditor\u4cgkarx.tmp_proj]
  Utilities\ProSymbolUtilities.cs(118,31): error CS7036: There is no argument given that corresponds to the required formal parameter 'dms' of 'CoordinateDMS.TryParse(string, bool, out CoordinateDMS)' [C:\Jenkins\workspace\MT\3.0\ArcGIS Pro 2.1\military-symbol-editor-addin-wpf\source\ProSymbolEditor\u4cgkarx.tmp_proj]
```

These error messages appeared when running our MT build from Jenkins.

FYI our MT builds will fail until this is addressed:
@lfunkhouser @topowright @kgonzago @dfoll @csmoore @BobBooth

**Comment by lfunkhouser** [comment]
Team, why is a change in the Coordinate Conversion add-in only affecting Military Symbol Editor?

**Comment by csmoore** [comment]
Good question - I suspect the difference is that since the Military Symbol Editor was (1) Pro-only (2) Used Lines/Multipoints and (3) pre-dated this change, it passed around Pro Map Points internally where the others were ArcMap/Pro so used text strings.

The CC code could have been written/changed to not change the public interface and require changes everywhere and also behave more like the standard .Net TryParse

```
public static bool TryParse(string input, out CoordinateDMS dms)  
{
    TryParse(input, out dms, false);
}
```

```
public static bool TryParse(string input, bool displayAmbiguousCoordsDlg, out CoordinateDMS dms)  
...
````

Or make it optional:

```
public static bool TryParse(string input, out CoordinateDMS dms, bool displayAmbiguousCoordsDlg = false)  
...
````

**Comment by lfunkhouser** [comment]
Thanks @csmoore. I'm moving this issue to the Coordinate Conversion repo since that is where the update to the code needs to happen.

**Comment by lfunkhouser** [comment]
This issue was moved to Esri/coordinate-conversion-addin-dotnet#496
