### ISSUE TITLE
Adding coordinates via keyboard does not work

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbol-editor-addin-wpf#229]
### Background: 

Users have the ability to add coordinates manually on the enter coordinates tab

### Current State: 

Coordiantes are not showing as accurate to allow the coordinates to be added from keyboard: 
![image](https://user-images.githubusercontent.com/5488313/39852069-521078a4-53e8-11e8-9877-c79eb4a37a41.png)

### Expected Results

Coordinates are entered into the add coordinates in the same formats that are supported in the other add-ins.

**Comment by dfoll** [comment]
With MSE build 11 on 2.2 final this is no longer an issue
