### ISSUE TITLE
MSE schema being added to the project more than once

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbol-editor-addin-wpf#230]
### Tasks to be done 13 June
- [x] Fix the issue with multiple datasets being added
- [x] Verify the addin is working as expected for adding the schema
 
### Background
When a user wants to use the MSE they have to add the schema to their local project. Currently this is happening multiple times for some odd reason. 

### Current State
The schema is being added multiple times. 
![image](https://user-images.githubusercontent.com/5488313/39852133-ccd47cd4-53e8-11e8-86d4-6ea77dc8aed4.png)

### Expected Results
The add-in understands that it has already added the schema to the current project

**Comment by topowright** [comment]
As the add-in is enabled the prompt to add another schema happens multiple times. 
![image](https://user-images.githubusercontent.com/5488313/39852180-13d23022-53e9-11e8-9a16-9c7ffb0b720f.png)
### Steps to reproduce: 

1. - Add the schema
2. - Add a point of sometype
3. - Search for another type
4. - Choose that new type and try and add it to the map

Result
The system will prompt the user to create a new schema

**Comment by csmoore** [comment]
This should be addressed in PR #239 - this bug that was introduced (by me - :innocent: ) in PR #227

**Comment by ACueva** [comment]
Verified in Pro 2.2 daily, MT Build 42.  Only 1 database is being added to the project.
![2018-06-14_7-41-16](https://user-images.githubusercontent.com/3093940/41419383-b968bf6e-6fa6-11e8-83f5-15aa369eb4d9.jpg)

**Comment by ACueva** [comment]
FYI @topowright 
![2018-06-14_13-12-48](https://user-images.githubusercontent.com/3093940/41435828-dc91b27e-6fd4-11e8-85b0-a6bd82b37be7.jpg)

Verified from the Single add-in as well:
![2018-06-14_13-17-31](https://user-images.githubusercontent.com/3093940/41436198-bdd35a1c-6fd5-11e8-8a45-917dde6a4e93.jpg)

**Comment by lfunkhouser** [comment]
@ACueva to verify that this is also fixed after switching to 2525D schema

**Comment by ACueva** [comment]
Verified with 2525D. 
![2018-06-19_14-21-53](https://user-images.githubusercontent.com/3093940/41625000-37a99398-73cc-11e8-9813-dbc48e98dbf1.jpg)
![2018-06-19_14-22-47](https://user-images.githubusercontent.com/3093940/41625005-38f17cde-73cc-11e8-9dab-35a7008535b9.jpg)
