### ISSUE TITLE
ArcGIS Pro crashes when symbol added using Coordinates tab

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-symbol-editor-addin-wpf#254]
### Steps to Reproduce:
1. Search for and select a symbol in the Search tab
2. Click the Enter Coordinates tab
3. Paste in a set of coordinates, such as 40.4406° N, 79.9959° W
4. Click Add Coordinate(s) to Map
5. ArcGIS Pro crashes

### Version
ArcGIS Pro version 2.2
August 2018 release, Military Tools version 3.1

**Comment by dfoll** [comment]
cannot reproduce with Military Tools 3.1.0.100 and ArcGIS Pro 2.2.0
