### ISSUE TITLE
Serifs Are Appearing On Some Text

### ISSUE THREAD

**Issue by abouffard** [Esri/military-symbol-editor-addin-wpf#26]
The text in some symbols displayed in the editor are being drawn with a serif font, even though the original SVG files are sans serif.  The same symbol when drawn on the map is correct - sans serif.

![serif](https://cloud.githubusercontent.com/assets/4564846/14376617/33ebd424-fd30-11e5-8e84-7c0858c3fe77.JPG)

**Comment by csmoore** [comment]
This got fixed with #139 / #142 - closing

![image](https://cloud.githubusercontent.com/assets/3090809/22930455/512d9b90-f28e-11e6-9f3f-38e13fc6e811.png)
