### ISSUE TITLE
Symbol Editor compatibility with Military Overlay Information Model Layer Package (lpkx)

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/military-symbol-editor-addin-wpf#28]
This is the Military Overlay Layer Package, which I just wrote solutions pages for. I don't know what else needs to be done to have the editor work with this, but it contains the same Military Overlay gdb schema. Not a showstopper, but should be done at some point.

Until released, you can load the layer package here: https://github.com/Esri/military-features-data/blob/master/data/mil2525d/overlay_templates/layerpackages/MilitaryOverlay.lpkx

**Comment by tlauver** [comment]
Previously we had a message that popped up that could take the user to a website to download the overlay template if it didn't detect the Military Overlay database.  If we add the capability to add in the layer package if the schema isn't detected, do we want to give the user a choice to go to the website to get the overlay as well?  Or just ask if they want to add the layer package?

**Comment by csmoore** [comment]
We probably no longer need this - we just want to make sure we don't do anything (like the deferred "go to share overlay task") that assumes the add-in will only be running with MilitaryOverlay template now.

It would be good if we could figure out where to put an "About" button/box that would still take you to the latest template/doc at: http://esriurl.com/AFDMilitaryOverlay  

The released lpkx is here btw in case you don't have: http://solutions.arcgis.com/defense/templates/military-overlay-information-model/ ( @Dbarnes1 - not sure what the short URL is for this)

**Comment by tlauver** [comment]
Thanks, then I'll just give the option for adding the lpkx file.  We should add another task/issue for the "About" button I guess.

I'll grab the latest lpkx, it needs to be included in the add-in to work (at least at the moment).

**Comment by Dbarnes1** [comment]
esriurl.com/MilitaryOverlayInformationModel short url for the information model

**Comment by csmoore** [comment]
Assigning to @Dbarnes1 to verify the 2 cases:

1. Project has MOIM loaded and addin is enabled / works as expected
2. Project does *not* have MOIM and addin adds layer package to project

**Comment by csmoore** [comment]
Assigning to @BobBooth to possibly verify with #30 (while Dan is busy)

**Comment by BobBooth** [comment]
Testing reveals a small issue - when I created a new, blank project and started searching for symbols, I did get the "do you want to add the layer package" message. However, I had no map in my project yet, so I got the "please add a map and try again" message. All very well so far. I added a map. Then I changed it coordinate system to WGS 84 UTM zone 12 N (the default coordinate system of new maps seems to be Web Mercator (auxiliary sphere) which is frowned upon). After I did this, I went back to the add in, searched, and did not immediately get the "military schema not detected" message. I double-clicked the same symbol I had picked before. Nothing. It seems you have to choose a different symbol to trigger the "add layer package" logic.  Can we make it so clicking any of the symbols triggers it?

**Comment by BobBooth** [comment]
I will mark this verified, as it works. I will add an additional issue to fix layer for the enhancement to smooth that little bump.
@csmoore @Dbarnes1 @tlauver
