### ISSUE TITLE
Add Country/CountryCode to Text Attributes Tab

### ISSUE THREAD

**Issue by csmoore** [Esri/military-symbol-editor-addin-wpf#29]
Country/CountryCode isn't a 2525 label attribute (although that would be useful), but it is probably an important attribute we should let the end-user set on that tab.

**Comment by csmoore** [comment]
Can we sort these alphabetically by name (versus code)? I'm having a really hard time finding countries:

![image](https://cloud.githubusercontent.com/assets/3090809/15408097/7441fd38-1ddc-11e6-9cad-8f5f7fd4753a.png)

**Comment by tlauver** [comment]
I think so?  Another thing I could look into.

**Comment by csmoore** [comment]
Verified in #69 (with sorted names):

![image](https://cloud.githubusercontent.com/assets/3090809/15679228/12294cf4-271f-11e6-9fe3-2fcd8537739d.png)
