### ISSUE TITLE
For symbols with built-in affiliation, maybe set affiliation Identity/attribute

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-symbol-editor-addin-wpf#30]
Some symbols (Maneuver area  Axis of Advance, Main Attack, Friend) 
draw with the Unknown (yellow) symbol color if you pick them from the list and start drawing.
Maybe we could automatically set the attribute to Friend for these features?
![image](https://cloud.githubusercontent.com/assets/3801392/14389050/c98babb4-fd7e-11e5-96bf-95912a925f16.png)

**Comment by csmoore** [comment]
@BobBooth - forgot to let you know this was ready to verify using the daily build location. 

One note the preview for some of these won't change color (there is only 1 version for control measures), but the affiliation attribute and symbol on the map should now reflect the symbol name if it has "Friend" etc. for line/area (I believe it only did points before)

**Comment by BobBooth** [comment]
Verified.  I saw that, thought it was an error at first, but I see obstacles can be tagged "Friend" but should be drawn in green anyway.
