### ISSUE TITLE
Should we create Military Tools Pro Top-Level Ribbon tab?

### ISSUE THREAD

**Issue by csmoore** [Esri/military-symbol-editor-addin-wpf#38]
This addin (and the other Military Tools Pro projects) currently have the tab commented out : https://github.com/Esri/military-symbol-editor-addin-wpf/blob/dev/source/ProSymbolEditor/Config.daml#L16 

So I was wondering if/when we should plan on adding this to its own Pro tab: "Military Tools" (or other agreed upon name) for all of the Military Tools for ArcGIS in Pro.  Just wanted to get this discussion started

@topowright @nfeuerstein @conklinbd @lfunkhouser

**Comment by csmoore** [comment]
I never heard back on this - so moving to deferred

**Comment by conklinbd** [comment]
@csmoore 
@topowright has worked on this. There is supposed to be Military Tools top Level tab we need to have your tool registered to.

**Comment by csmoore** [comment]
Thanks - I just noticed [this](https://github.com/Esri/military-tools-for-arcgis/blob/dev/source/MilitaryToolsToolbar/ArcGISProAddinMAToolbar/Config.daml#L29) yesterday and submitted Issue+PR with update: 

https://github.com/Esri/military-tools-for-arcgis/issues/20
https://github.com/Esri/military-tools-for-arcgis/pull/21

Closing this issue/question
