### ISSUE TITLE
Transfer labels to another repo

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-symbol-editor-addin-wpf#39]
_From @lfunkhouser on March 28, 2016 19:25_

_Copied from original issue: Esri/coordinate-conversion-addin-dotnet#86_

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/visibility-addin-dotnet#49

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-tools-for-arcgis#5

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/air-c2-cop#1

**Comment by csmoore** [comment]
Thanks @lfunkhouser

**Comment by ACueva** [comment]
This issue was moved to ArcGIS/military-tools-for-arcgis-build#8
