### ISSUE TITLE
schema mil2525d

### ISSUE THREAD

**Issue by kaosklin** [Esri/military-symbol-editor-addin-wpf#393]
i have one question regarding the schema i get the symbol 
![10060240001100000813](https://user-images.githubusercontent.com/24214515/74043777-c49a4780-49a8-11ea-9b68-66c3fa9fe1f1.png)
but i want this symbol 
![10060240001100000813(1)](https://user-images.githubusercontent.com/24214515/74043810-d4b22700-49a8-11ea-9a63-dd7660f9960f.png)
there is some key that i have to change to get it? the code is the same

**Comment by csmoore** [comment]
Not sure what version you are using, but a config setting was added to this at 2.4 on the Pro Dictionary Symbology Tab (Layer | Symbology)

![image](https://user-images.githubusercontent.com/3090809/74046701-091fe600-499d-11ea-8361-9c356cb3d261.png)

**Comment by kaosklin** [comment]
> 
> 
> Not sure what version you are using, but a config setting was added to this at 2.4 on the Pro Dictionary Symbology Tab (Layer | Symbology)
> 
> ![image](https://user-images.githubusercontent.com/3090809/74046701-091fe600-499d-11ea-8361-9c356cb3d261.png)
ohh, havent seen that
perfect man, thanks.
