### ISSUE TITLE
Support Internationalization (I18n) / Create Resource Dictionary

### ISSUE THREAD

**Issue by csmoore** [Esri/military-symbol-editor-addin-wpf#394]
The Military Symbol Editor was not original written to support Support Internationalization (I18n) through the use of a project Resource Dictionary.  For example this (and all other) labels [are hard coded](https://github.com/Esri/military-symbology/blob/dev/source/ProSymbolEditor/Views/SymbolView.xaml#L55) 

To support I18n, the following is needed:

1. Convert View Text to use Resources
2. Convert MessageBox/Warnings to Resources

@lfunkhouser FYI

**Comment by dfoll** [comment]
@sumitzarkar would you please take a minute to review this and estimate

**Comment by sumitzarkar** [comment]
@lfunkhouser @csmoore @dfoll 

We have committed the work in progerss code for this ticket [commit link](https://github.com/Esri/military-symbology/commit/c2d72b3380af001ca975be83f377dccc606986d8)

**Comment by sumitzarkar** [comment]
@lfunkhouser @csmoore @dfoll

We have committed the work in progerss code for this ticket [commit link](https://github.com/Esri/military-symbology/commit/988a0b1ae6cc6de37d984e0cd5934221fac3d726)

**Comment by csmoore** [comment]
@sumitzarkar - thanks for sharing the current progress.

I am concerned that the new resources names are not meaningful and will be difficult to maintain.

[For example](https://github.com/Esri/military-symbology/commit/988a0b1ae6cc6de37d984e0cd5934221fac3d726#diff-80f8753f20c8946f60a557549ffef6f6L443)
Old:     Content="Add Favorite"
New:   Content="{x:Static prop:Resources.**SymBtn2**}"

BetterName: Content=prop:Resources.**SymBtnAddFavorite**

Would it be possible to switch the name endings (1, 2, 3, etc.) instead to the name of the original string (ex. "AddFavorite")

**Comment by sumitzarkar** [comment]
@lfunkhouser @csmoore @dfoll

We have committed the work in progerss code for this ticket [commit link](https://github.com/Esri/military-symbology/commit/a09b4e84b08f84baf0b52712c0a43b68147a747d)

@csmoore 
We are also implementing your above feedback.

**Comment by sumitzarkar** [comment]
@lfunkhouser @csmoore @dfoll 

We have pushed the final code drop for #395 [pull request link](https://github.com/Esri/military-symbology/pull/395)

**Comment by csmoore** [comment]
Thanks for the update, we'll start having a look

**Comment by ashutoshverma-ct** [comment]
@csmoore @lfunkhouser @dfoll 

In the code, we found dependency on Layer Packages as shown in the below image. Should we keep it as shown or is there any change needed?

![Layer Packages](https://user-images.githubusercontent.com/22743029/77517542-5222ef80-6ea2-11ea-8c5c-b51fc5c0ed4f.PNG)


Moreover, there are layers and fields name defined as shown in the images. We have kept them as it is.  Please let us know if any change is needed.
| Layer Name | Field Name |
| - | - |
| ![Layers](https://user-images.githubusercontent.com/22743029/77517839-c9588380-6ea2-11ea-9f73-742ca4c9c106.PNG) | ![FieldNames](https://user-images.githubusercontent.com/22743029/77517834-c8275680-6ea2-11ea-9806-965f3f4ef251.PNG) |

**Comment by csmoore** [comment]
@ashutoshverma-ct - that is a good find. For now, we aren't sure exactly how these layer packages will be internationalized, so for now can you just add a comment to these sections with something like `"TODO: Adjust this section when Layer Package Internationalized"` 

Thanks for finding this and checking on.

**Comment by ashutoshverma-ct** [comment]
@csmoore

The above comments are noted and we will incorporate them in the code.
We will deliver the code after the implementation.

**Comment by sumitzarkar** [comment]
@csmoore @lfunkhouser @dfoll 

We have updated code for this ticket [commit link](https://github.com/Esri/military-symbology/pull/396/commits/ba66acc84cc476ea76f4880887a308dfa7b074ca)

1. Reverting changes to layers
2. Added missing resource “default”

**Comment by csmoore** [comment]
@sumitzarkar Thanks for the updates - we'll do the acceptance testing once the project gets switch to the "Pro2.6" version of [Coordinate Conversion ](https://github.com/Esri/military-symbology/pull/395#issuecomment-604367006)

**Comment by sumitzarkar** [comment]
@lfunkhouser @csmoore @dfoll 

We Switched Project to the "Pro2.6" version of Coordinate Conversion - [Commit link](https://github.com/Esri/military-symbology/pull/396/commits/20a375c0b8e59c099cfa5d055aefd195d92b01d5)

**Comment by csmoore** [comment]
This has been tested and accepted - please note the concerns mentioned in https://github.com/Esri/military-symbology/pull/396#issuecomment-609876256 for future work.
