### ISSUE TITLE
Modify workflow description is slightly confusing to users

### ISSUE THREAD

**Issue by csmoore** [Esri/military-symbol-editor-addin-wpf#41]
Modify workflow doesn’t make it clear that this is a symbol from the add-in not a symbol from the map.

Just need to clarify the language a bit here: https://github.com/Esri/military-symbol-editor-addin-wpf#modify-a-symbol 

Feedback from @kerryrobinson

**Comment by kerryrobinson** [comment]
Wherever the doc says "after you've selected a symbol", that could be interpreted as selecting the actual feature on the map, and then "Modify a Symbol" could be interpreted to mean modifing the symbol of the feature selected on the map.  

Recommend making the doc clear that this tool is only for creating symbols, the worfklow for modifying an existing symbol is to use the Attributes pane, and changing the doc from "after you've selected a symbol" to "after you've selected a symbol in the Search tab" (or something similar).

**Comment by BobBooth** [comment]
@kerryrobinson - addressed this in PR:
https://github.com/Esri/military-symbol-editor-addin-wpf/pull/43
Once Travis merges, could you have a look?

**Comment by kerryrobinson** [comment]
@tlauver , looks great!
