### ISSUE TITLE
Enhancement: Allow import of existing feature templates to Favorites list in MSE

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-symbol-editor-addin-wpf#44]
Someone who has already gone to the trouble to create some features outside of the military symbol editor might want to be able select some of them and import them to their Favorites list.

**Comment by csmoore** [comment]
We'll might want to think about how to incorporate a workflow for select and existing feature and setting the symbol editor's state from it first (and then it would just be a matter of adding to the favorites at that point).

The tricky thing about this workflow of being able to select an existing feature is: how do you differentiate between selecting a feature to modify its attributes vs. creating a new feature ("create" feature mode vs. "modify" feature mode - currently we were only planning on doing "create" mode)

**Comment by BobBooth** [comment]
There could be a "Get symbol from existing feature" button - awful name, I know, possibly on the Search tab, near the bottom, or maybe on the kitchen sink tab.

**Comment by BobBooth** [comment]
This is partly covered by the existing "Modify" tab, which allows manual selection of one feature.
Since you can export the attribute table (or the attribute table for selected features) and get the code values (aside - I thought maybe you'd see the verbose equivalents from the coded value domains), having a Python script to read a CSV file or table of these fields and their codes and write out a favorites JSON file gets us most of the way there for the batch workflow.

**Comment by lfunkhouser** [comment]
Closing. As Designed.
