### ISSUE TITLE
Use semantic version numbers for release tracking

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-symbol-editor-addin-wpf#47]
To be consistent with other work we should use semantic version numbers for release tracking.
e.g. MVP1 = 1.0.0

**Comment by csmoore** [comment]
The [MVP 1 release](https://github.com/Esri/military-symbol-editor-addin-wpf/releases) necessary doesn't map to an actual download item (which indeed should have a semantic version and map to a github release with the same version) - but there may be additional/initial releases like this beyond the semantic versioned ones. 

Or we can always use the semantic versioning - but this one would be more like 0.0.1 or something (and likely still have the same title).

**Comment by BobBooth** [comment]
My thought is, if we are including it in the Military Overlay download and documenting it on that template's page, we need to be able to identify the version included. MVP1, MVP2 etc... is fine for versioning the GitHub repo, but we still need to be consistent for stuff that goes out via solutions pages. Maybe use MVP nomenclature for internal break points in the dev process and semantic versioning for each time we release to solutions (and I'm fine with this first one being 0.0.1 for that).

**Comment by csmoore** [comment]
OK, once we have tested/checked out the new MilitaryOverlay1.1.0 download item you created - we can create a new Github release for this - with version 0.1.5 if OK (trying to communicate MVP 1.5 here - I'll rename the previous MVP 1 release 0.1.0 now) 

The main goal is to ensure we can readily map the download item (MilitaryOverlay1.1.0 ?) to the GitHub release items included - so will there be a table somewhere of the template version mapped to Github release versions (unless that is what you are trying to create here)?

For repos where the repo is the release, this is more straightforward - ex: https://github.com/Esri/solutions-geoprocessing-toolbox/releases 

But for others, where only a part of the repo is used (or multiple parts of multiple repos) things are more complicated, but this does bring up a good point that we need to work better to ensure this mapping exists and is consistent, ex. we have this same issue here with the other part of Military Overlay: https://github.com/Esri/military-features-data/releases

**Comment by csmoore** [comment]
@tlauver - once we get the version decided we'll fix in the assembly as well (and change the author to Esri):

![image](https://cloud.githubusercontent.com/assets/3090809/14887544/54200df6-0d24-11e6-845f-909d3623a247.png)

**Comment by csmoore** [comment]
I created release 0.1.0 and edited title of previous release: https://github.com/Esri/military-symbol-editor-addin-wpf/releases.

I added a new issue #53 for the Addin/assembly name/version/description issues noted in screenshot above

**Comment by BobBooth** [comment]
Verified.
