### ISSUE TITLE
Do we want to sign Pro addins?

### ISSUE THREAD

**Issue by csmoore** [Esri/military-symbol-editor-addin-wpf#48]
Do we have any plans to sign these addins? We can figure out how to do (we did this with MOLE editor), but it will definitely complicate the build process.

I would be inclined not to worry about - but this dialog may be somewhat alarming to our users.

![image](https://cloud.githubusercontent.com/assets/3090809/14887251/ea8a8c1e-0d22-11e6-8f2e-e85e7c22653a.png)

Just bringing this up as a known deferred issue for now

**Comment by BobBooth** [comment]
@csmoore I think we should, yes.

**Comment by csmoore** [comment]
This just became a requirement for the June release so we'll need to crack open the release and get the addins signed

**Comment by csmoore** [comment]
There is now a process for signing solutions addins and the addin has been signed for next (June) Solution Page release
