### ISSUE TITLE
Provide visual indication on UI of when it is disabled vs. enabled

### ISSUE THREAD

**Issue by csmoore** [Esri/military-symbol-editor-addin-wpf#51]
We should provide some better indicator/feedback of when the Addin form is disabled - so this is clearer to users

Currently Enabled:
(Note: we should also **enable** the search box - looks disabled)

![image](https://cloud.githubusercontent.com/assets/3090809/14982847/6c18f580-1107-11e6-84f0-3141e71fbc7d.png)

Currently Disabled:
We should add/change a label - even change the Search Box label to ("Search/addin disabled - please load military overlay")
   
![image](https://cloud.githubusercontent.com/assets/3090809/14982813/23f4aa7e-1107-11e6-817c-9dd65e17d931.png)

**Comment by csmoore** [comment]
Meant to also mention - this is related to #49 (trying to figure out from bug report screenshots if/why addin is disabled)

**Comment by csmoore** [comment]
Verified search box is enabled now and that new "add lpk" logic makes the rest OBE:

I do occasionally get a kick out of the symbol search results returned ("friend icebergs" "many bergy bits")

![image](https://cloud.githubusercontent.com/assets/3090809/15407024/fa2d439a-1dd6-11e6-802f-0f58e5fed160.png)

**Comment by BobBooth** [comment]
Aren't most icebergs hostile?

**Comment by BobBooth** [comment]
Might need to check them with an Identification Friend or Floe system...
