### ISSUE TITLE
Unit tests needed

### ISSUE THREAD

**Issue by ACueva** [Esri/military-symbol-editor-addin-wpf#56]
Build process requires unit tests.
- [x] Update Readme.md with instructions on how to run the unit test.

I did try to run existing test, however I got the following error:

``` command
c:\test\military-symbol-editor-addin-wpf\source>vstest.console.exe C:\test\military-symbol-editor addin-wpf\source\SymbolEditorUnitTests\bin\Release\SymbolEditorUnitTests.dll
Microsoft (R) Test Execution Command Line Tool Version 12.0.21005.1
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Passed   CheckLayerForSymbolSetTest
Failed   CoordinateTypeTest
Error Message:
   Test method SymbolEditorUnitTests.SymbolEditorTests.CoordinateTypeTest threw exception:
System.Exception: Host must be a 64 bit executable.  Check target platform.
Stack Trace:
    at ArcGIS.Core.Hosting.Host.Initialize()
   at SymbolEditorUnitTests.SymbolEditorTests.CoordinateTypeTest() in c:\jenkins\military-tools-for-arcgis-build\workspace\military-symbol-editor-addin-wpf\source\SymbolEditorUnitTests\SymbolEditorTests.cs:line 47


Total tests: 2. Passed: 1. Failed: 1. Skipped: 0.
Test Run Failed.
Test execution time: 0.9995 Seconds

c:\test\military-symbol-editor-addin-wpf\source>

```

**Comment by csmoore** [comment]
@ACueva - this is ready to verify - the instructions have been updated at link below with how to run this as a x64 process (required by Pro SDK dependencies) - so this command will differ slightly from the other repos (not sure why they would not have Pro dependencies):

https://github.com/Esri/military-symbol-editor-addin-wpf/blob/dev/README.md#developers-1

**Comment by csmoore** [comment]
OK to close? (Will close if I don't hear back)

**Comment by lfunkhouser** [comment]
@ACueva please verify

**Comment by ACueva** [comment]
@csmoore Tests have been implemented.
Getting the following Warning:

```
Warning: No test is available in SymbolEditorUnitTests\bin\Release\SymbolEditorUnitTests.dll. Make sure that installed test discoverers & executors, platform &
framework version settings are appropriate and try again.
```

I'm updating Visual Studio and trying again.

**Comment by ACueva** [comment]
@csmoore Looks like it's still broken.  Still experiencing the same issue even after updating Visual Studio.

**Comment by csmoore** [comment]
Based on the number of web reports of similar vstest problems **until** VS2015 Update 2, we may have to defer this until the build server can be upgraded to a newer version. We have to use vstest to be able to run as x64 (because of Pro dependencies - not sure how the other projects got around these or if they have any).

If no objections, marking this as deferred until build server at VS2015 Update 2 or higher.

**Comment by lfunkhouser** [comment]
Closing. Unit tests will be written with new functionality and integrated to run automatically.
