### ISSUE TITLE
Change Built Addin Name to MilitarySymbolEditor.addinX version to 1.0

### ISSUE THREAD

**Issue by csmoore** [Esri/military-symbol-editor-addin-wpf#61]
It was requested (by @nfeuerstein and @topowright) that we:

- [x] Change "**Pro**SymbolEditor.esriAddInX" --> "**Military**SymbolEditor.esriAddinX (Addin/Name should not contain Product name)
- [x] Rename the product version to 1.0.0 (can't post versions < 1.0 to downloads - only tech preview - site)
- [x] Fix the name references in the https://github.com/Esri/military-tools-for-arcgis 

We'll need to make these changes, re-sign addin, and update download if this is still to be included with June release ( @Dbarnes1 @BobBooth FYI)

**Comment by BobBooth** [comment]
@csmoore & @Dbarnes1 - I have updated the readme and the affected solutions pages. Let me know when the renamed/re-signed version is available and I'll zip and hand off to @Dbarnes1 and submit the PR to Solutions pages.

**Comment by csmoore** [comment]
@BobBooth - working on now - will cc you on the request so you can follow the status

**Comment by csmoore** [comment]
Name changed in toolbar manual register script with: https://github.com/Esri/military-tools-for-arcgis/pull/23  (I couldn't find any other references to this name, so hopefully that is all of the changes required)

Closing this issue (but reopen if I missed something)
