### ISSUE TITLE
Symbol Preview Gap

### ISSUE THREAD

**Issue by csmoore** [Esri/military-symbol-editor-addin-wpf#65]
The gap between the UI inputs and the symbol preview is becoming more of an issue.

Unless someone already knows to scroll down to find, there is really no way to know it is even there - any way we can have another look at  trying to minimize this gap?

![image](https://cloud.githubusercontent.com/assets/3090809/15408756/d153d7d2-1ddf-11e6-9597-7f9b143c7ad9.png)

![image](https://cloud.githubusercontent.com/assets/3090809/15408769/e021ee16-1ddf-11e6-8591-bec195c655a1.png)

**Comment by tlauver** [comment]
I can look again, but not sure what else we can do.  The gap is there due to the control that allows for the panel to be docked horizontally or vertically and that changes the UI respectively based on the width of the panel.  There's also a large transparent buffer around each SVG, which also causes a problem with getting the symbol closer to other controls.

**Comment by nfeuerstein** [comment]
I changed from Enhancement to Bug - the gap is massive in some cases and there is nothing telling me to scroll down.  Then, if I do happen to figure out that I need to scroll down, I'm so far from the options to customize the symbol that it takes away from the WYSIWYG point of the add-in.

**Comment by csmoore** [comment]
We can have another look - as Travis mentioned the original requirement that the addin work well when docked to the left (vertical) or bottom (horizontal) drove some of the weirdness. But even worst/short-term case if we can't remove the gap we can maybe put a splitter control in that would let the user remove the gaps themselves.

But the gap definitively seems worse on some tabs so maybe that can offer a clue to what is going 
wrong in the layout - worst case here :

![image](https://cloud.githubusercontent.com/assets/3090809/21226908/aa3054a8-c2a5-11e6-86fa-77b14a11539d.png)

**Comment by nfeuerstein** [comment]
@csmoore I like the idea of a splitter so the user can manually shorten the gap as a workaround.

**Comment by csmoore** [comment]
Addressed in #123, I also made the search list a little smaller so things would generally fit on one pane.

![image](https://cloud.githubusercontent.com/assets/3090809/21572849/005609d8-ceac-11e6-89c6-5c041d166e5d.png)

There is still a small gap if there are no upper/lower symbol modifiers, but this gap is there in the original/source symbols/SVGs to accommodate modifiers if present. Screen shots of how this looks now (with/without these modifiers):

![image](https://cloud.githubusercontent.com/assets/3090809/21572794/6edfd84e-ceab-11e6-98ea-9822458101a9.png)

![image](https://cloud.githubusercontent.com/assets/3090809/21572799/7ce85fc4-ceab-11e6-884e-4ed69cc573ab.png)

Example gap/buffer around source symbols/SVGs/frames:
![image](https://cloud.githubusercontent.com/assets/3090809/21572808/9264de4a-ceab-11e6-9098-8a8e700b2f71.png)

**Comment by Dbarnes1** [comment]
@csmoore verified fixed, closing: 
![image](https://cloud.githubusercontent.com/assets/13024357/21660969/ac33e0f8-d286-11e6-89f9-be9d0012d9a0.png)
