### ISSUE TITLE
Add About Form with version # and link to Template

### ISSUE THREAD

**Issue by csmoore** [Esri/military-symbol-editor-addin-wpf#67]
I believe this is in our MVP 3 stories, but just capturing here so we don't forget.

Add About Form (perhaps launched from "hamburger button" with version # and link to Template ( [Military Overlay](http://esriurl.com/AFDMilitaryOverlay) and [Military Overlay Information Model](http://esriurl.com/MilitaryOverlayInformationModel) ).

We frequently get asked: "how do I know what version of the addin is installed"

**Comment by Dbarnes1** [comment]
![image](https://cloud.githubusercontent.com/assets/13024357/16052167/d3576bc4-3217-11e6-9f84-a0b170d941c1.png)
Verified, closing.
