### ISSUE TITLE
If you don't have a map, logic to trigger "add layer package" requires hitting a new symbol

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-symbol-editor-addin-wpf#70]
Testing issue #28 (https://github.com/Esri/military-symbol-editor-addin-wpf/issues/28) reveals a small issue - when I created a new, blank project and started searching for symbols, I did get the "do you want to add the layer package" message. However, I had no map in my project yet, so I got the "please add a map and try again" message. All very well so far. I added a map. Then I changed it coordinate system to WGS 84 UTM zone 12 N (the default coordinate system of new maps seems to be Web Mercator (auxiliary sphere) which is frowned upon). After I did this, I went back to the add in, searched, and did not immediately get the "military schema not detected" message. I double-clicked the same symbol I had picked before. Nothing. It seems you have to choose a different symbol to trigger the "add layer package" logic. Can we make it so clicking any of the symbols triggers it?

**Comment by csmoore** [comment]
It will probably be simplest just to clear the search selection if there isn't an active map.  Right after this is displayed (we should probably add a title to this warning message box also):

![image](https://cloud.githubusercontent.com/assets/3090809/21119102/faaed68e-c08e-11e6-894d-7a4ac597a7c2.png)

**Comment by csmoore** [comment]
Addressed this by adding title to message box - and adding message to search

![image](https://cloud.githubusercontent.com/assets/3090809/21443073/3cd6199e-c870-11e6-8024-d9225d432259.png)

![image](https://cloud.githubusercontent.com/assets/3090809/21443087/5d923e4c-c870-11e6-8708-aa7fb98e76dd.png)

**Comment by Dbarnes1** [comment]
verified
