### ISSUE TITLE
Rename tabs, to account for new "modify" tab for changing an existing feature

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-symbol-editor-addin-wpf#71]
The current "Modify" tab should be renamed "Symbol" and the current "Text" tab should be renamed "Label" to clarify what these tabs work on, and to allow the new tab for modifying the symbol for an existing feature to be called "Modify".
@csmoore @Dbarnes1 @tlauver

**Comment by csmoore** [comment]
We have had feedback from 2 people that the current "modify" tab is confusing so (time permitting) let's please implement this as part of the last MVP-2 cleanup items - we can then review at next sprint review and get feedback on.

**Comment by Dbarnes1** [comment]
@csmoore @tlauver @BobBooth verified in latest tests, closing: 
![image](https://cloud.githubusercontent.com/assets/13024357/16052070/55b1707a-3217-11e6-82ce-83ddc8ade9d4.png)
