### ISSUE TITLE
Move "Favorites" tab to right of tab list

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-symbol-editor-addin-wpf#72]
I find the "Favorites" tab interrupts the symbol creation workflow.  I tend to start at Search, then want to change the symbol, but the next thing is "Favorites" which doesn't yet apply.
I think we should move the "Favorites tab to the right end of the tab list (after Enter Coordinates).
Opinions?
@tlauver @csmoore @Dbarnes1

**Comment by Dbarnes1** [comment]
This has been fixed, closing.
