### ISSUE TITLE
If one layer with correct schema is on map, offer to get others from same source

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-symbol-editor-addin-wpf#73]
When you use the military symbol editor it checks to see if the Military Overlay schema is available. If you have one layer on your map with the correct schema, it would be nice if that could be detected and the add-in could offer to add the other layers (either immediately or on an as-needed basis).

**Comment by tlauver** [comment]
Right now it's all or nothing with the lpk - you can't pick and choose which layers/feature classes to add.  If it already exists, it'll add a duplicate with a _2 on the name.  We'd have to ditch using lpk and use something else, or the SDK would need to be changed.

**Comment by BobBooth** [comment]
Could have a single schema-only LPK for when there are no layers, and individual feature class LPKs for when one is missing... but actually what I meant was, when you have a layer on the map with the right schema, that implies that there exists a GDB that may have the other required layers (maybe not invariably, but in many cases) so we can offer to add the layers from the source GDB of the layer that is present.
