### ISSUE TITLE
Assembly dll properties different from addin

### ISSUE THREAD

**Issue by csmoore** [Esri/military-symbol-editor-addin-wpf#77]
This is likely an issue with all of the MilitaryTool Addins, but I noticed the dll properties differ from the addin's:

We should fix & see if there is some way to keep the daml and assemblyinfo in synch.

![image](https://cloud.githubusercontent.com/assets/3090809/16013608/1e4be784-315c-11e6-8143-4cd0c70559ee.png)

**Comment by csmoore** [comment]
Update: To get to the folder/file/dialog shown above ( @NatalieCampos ) :

1. Open File Explorer
2. Paste `%LOCALAPPDATA%\ESRI\ArcGISPro\AssemblyCache\{4ff462b0-2910-47f3-b6fd-d1d17e5f7dfc}` into the folder box
3. Right Click: MilitarySymbolEditor.dll
4. Click Properties and then "Details" tab 

Note: This was addressed for all of the addins with the version update to 2.1

**Comment by NatalieCampos** [comment]
@csmoore So I pasted the location above after installing this mornings build.... and I dont have that last folder {4ff462b0-2910-47f3-b6fd-d1d17e5f7dfc} in my Assemby Cache folder....

This is what I have.

**Comment by NatalieCampos** [comment]
Ok I got it.  The below graphic is what I have. Closing issue.

![image](https://cloud.githubusercontent.com/assets/5116835/26595297/c707d608-451f-11e7-8009-d19f32389ba8.png)
