### ISSUE TITLE
Selection Issues 

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/military-symbol-editor-addin-wpf#78]
1. When trying to select a feature directly from the Add-in using the Select button in the Modify tab, the features on the map aren't being selected. 

![image](https://cloud.githubusercontent.com/assets/13024357/16051431/afe18150-3214-11e6-993f-dc5496a399ec.png)
1. After selecting a feature using the core Select tool, and then unselecting the feature, the "Save Edits" button still exists in the symbol editor in the Symbol and Label panes. This is ok. However, when clicking on this button after features are no longer selected, an empty error dialogue pops up: 
   ![image](https://cloud.githubusercontent.com/assets/13024357/16051593/3dc29e1e-3215-11e6-8a06-d3022b8de1f9.png)
2. Not sure if this is supposed to work or not, but when selecting a feature on the map, and navigating to the Enter Coordinates pane in the Add-in, and entering a new set of coordinates, and selecting Save Edits, the symbol doesn't move to the new coordinate location, rather the Save Edits button seems to freeze. 
   ![image](https://cloud.githubusercontent.com/assets/13024357/16051905/915f03fe-3216-11e6-9b23-56783feebcf9.png)

**Comment by Dbarnes1** [comment]
@tlauver update: this is likely only an issue with Pro 1.3. I'm running on 1.3.5820. Not sure why this has changed between the versions.

**Comment by csmoore** [comment]
I tested this (on 1.4) and wasn't able to repro the phantom message box - but the "Save Edits" button definitely shouldn't be showing up when nothing selected so looking into this.

**Comment by csmoore** [comment]
Addressed in #123 to address (from original issue comments):

1. Clear selection if nothing selected by tool + Disable Save Edits button if nothing selected
2. Disable Enter Coords tab if editing

**Comment by Dbarnes1** [comment]
@csmoore validated fixed, closing.
