### ISSUE TITLE
Add Symbol to Map automatically creates Feature Template

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/military-symbol-editor-addin-wpf#82]
**User Story:**
After I've selected a symbol and clicked on the map, the Feature Template for that symbol is created and available in the Create Features window. Alternatively, I can export my favorites to Feature Templates. 

Another option would be a direct SIDC to feature template capability. This model would take the spreadsheet and produce feature templates/favorites. 

@tlauver do you know whether either of these options is possible or not? No worries if you don't have any info, I can look into it at that point.

**Comment by tlauver** [comment]
No, I don't believe I ever looked into whether feature templates were possible or not through that method.  I'd have to take a look at the Pro SDK.

**Comment by Dbarnes1** [comment]
https://pro.arcgis.com/en/pro-app/sdk/api-reference/#topic9917.html @csmoore  so I'm looking at the ArcGIS Pro 1.3 API reference guide, and I found several classes that are related to feature templates. Could we draw from this code to create feature templates from our existing favorites? or from adding a feature to the map in the pro symbol editor?

**Comment by csmoore** [comment]
@Dbarnes1 - nice job finding - that shows how to get a currently selected feature template and how to get a template from a layer, but not really how to add/create a new CreateFeature template to a layer (but that may indeed be there somewhere but just not leaping out at me - although someone with more experience with Pro SDK like @jmccausland or @deepinderdeol might be able to find)

**Comment by Dbarnes1** [comment]
Created related/more specific issue that can be used for CR entry here: https://github.com/Esri/military-symbol-editor-addin-wpf/issues/83
