### ISSUE TITLE
Geometry of the symbol (in Favorites) must be specified in the third to last place in the tags 

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-symbol-editor-addin-wpf#92]
In order for the Add-In to work with imported favorites, the geometry of the symbol must be specified in the third to last place in the tags (per TL). 
That is to say, if you import a JSON file without our tags, the values might all be correct, but the favorites display in the pane, but cannot be added to the map.
This was worked around in my export CSV to JSON script by hard-coding with the dummy values of "SymbolTags": "Point;Land Equipment;Land Equipment " 
It would be good to have this managed some other way, or have the tags generated and the geometry inserted by the add-in after the JSON is imported. 
From Favorites stress testing.

**Comment by csmoore** [comment]
Changing this label to enhancement - since this doesn't impact the end user

**Comment by csmoore** [comment]
When I looked at this, supporting having an end-user manually editing or creating these favorites JSON files outside of the application didn't seem like something we would want to "officially" support so to address this issue I went the route of trying to better state this and better document this behavior here:

* https://github.com/csmoore/military-symbol-editor-addin-wpf/blob/csm/bad-fav-issue-140/README.md#sharing-favorites 
* https://github.com/csmoore/military-symbol-editor-addin-wpf/blob/csm/bad-fav-issue-140/source/ProSymbolEditor/Models/SymbolAttributes/SymbolAttributeSet.cs#L112

**Comment by csmoore** [comment]
Unless someone feels strongly about this one, going to close "as designed"
