### ISSUE TITLE
Symbol Designer displays Favorite ID in top of Symbol Attribute Set table… why?

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-symbol-editor-addin-wpf#93]
The Symbol Designer displays the Favorite ID (a GUID, created by the editor simply to identify favorites in a machine readable format) in top of Symbol Attribute Set table… why?  It doesn't add anything to a user of the tool's understanding.  I would suggest just not showing the value.
From Favorites stress testing.
![image](https://cloud.githubusercontent.com/assets/3801392/18134645/1ade33a0-6f6d-11e6-9a89-e2cd73117f96.png)

**Comment by nfeuerstein** [comment]
@csmoore can the "favorite ID" guid be removed from the display?

**Comment by csmoore** [comment]
It can (very easily) - time permitting I was thinking about replacing this with a user-friendly name (like the style items have - ex. "Infantry : Friendly"), but for now we can just remove the line/GUID.

**Comment by csmoore** [comment]
Removed the FavoriteID row and added a friendly name to the Display/Label attributes row in #127 ex:

![image](https://cloud.githubusercontent.com/assets/3090809/21734434/5db5cf02-d431-11e6-8029-2a44388567f2.png)

**Comment by csmoore** [comment]
Some more testing showed that these names weren't being reliably updated. So I had to modify how this worked to get the name to update reliably - this is how it looks now (added Name row) - ready to verify in next build:

![image](https://cloud.githubusercontent.com/assets/3090809/21778016/8a635e08-d66f-11e6-8aa1-ac8f4bf48214.png)

**Comment by lfunkhouser** [comment]
Assigning back to @BobBooth to verify this has been resolved after the next build.

**Comment by BobBooth** [comment]
Verified.
