### ISSUE TITLE
Selecting non military features crashes addin (and Pro)

### ISSUE THREAD

**Issue by csmoore** [Esri/military-symbol-editor-addin-wpf#94]
Selecting a non military feature causes the addin and Pro to crash. 

Repro steps:
1. Open/Enable the Military Symbol Editor addin
2. Select a feature on the map that is **not** a military feature (does not have the field "symbolset")
3. Crash

Solution: this line needs a null check added:

https://github.com/Esri/military-symbol-editor-addin-wpf/blob/dev/source/ProSymbolEditor/ViewModels/MilitarySymbolDockpaneViewModel.cs#L1265 

**Note:** This is a significant bug that will affect anyone using the addin - the addin download should be updated after this is fixed. FYI @Dbarnes1

**Comment by csmoore** [comment]
Verified by @BobBooth 

@Dbarnes1 - it is highly recommended to update the downloads with this fix

**Comment by Dbarnes1** [comment]
@csmoore I'll make sure this new version gets in the latest military overlay

**Comment by csmoore** [comment]
@Dbarnes1 - you may also want to consider patching prior releases

**Comment by kgonzago** [comment]
Chris McGuire from Defense Services experienced this issue in the latest version of MSE. Re-opening to address/verify issue.

**Comment by csmoore** [comment]
I tried just a simple test and could not repro (non-mil features selected below). So if Chris could either:

1. Add some more detailed repro steps (and version tested with) or 
2. Try and debug from the latest in this repo 

to help us pinpoint.

![image](https://user-images.githubusercontent.com/3090809/36228074-1b89bd2e-11a1-11e8-9c41-618811e75b31.png)

**Comment by kgonzago** [comment]
Closing this since what the workflow gathered from Chris McGuire is slightly different from this issue.
