### ISSUE TITLE
Symbol Editor Add-In Confusing when working with new Military Overlay template

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/military-symbol-editor-addin-wpf#96]
When I use the current released version of the symbol editor add-in, which works with 2525D, with the new Military Overlay template, which has two schemas and two maps (one for 2525D and one for 2525 B change 2), I can add symbols to the 2525D map, but there is no warning or alert when I switch to the 2525Bc2 map.

I can:
1. find and customize D symbols in the add-in, and add them to the D map with the "add to map" function
2. switch to the B map, continue clicking on the map with the "add to map" function, and get no warning when no symbols are being added to the map
3. switch back to the D map, and see that the symbols were being added to that map all along.

I'm proposing some sort of warning when using the symbol editor add-in, particularly the new version which will work for both 2525D and 2525Bc2, when you switch away from the map that matches the schema in which you are working.

@csmoore I think that we are probably not going to break up the military overlay template that has both a D and Bc2 schema, map, etc. so the symbol editor add-in will need to work in a project that contains both of these schemas. 

@lfunkhouser @nfeuerstein  @dfoll FYI

**Comment by csmoore** [comment]
So just to clarify:

1. If there are multiple maps in a project (one map with one version of the schema/standard and one with the other or without)
2. If the user tries to add a military feature to a layer in a map that is not the current focus map
3. Issue a warning and cancel the operation

**Comment by Dbarnes1** [comment]
@csmoore yes, your comment clarifies the enhancement I'm trying to capture.

**Comment by csmoore** [comment]
Ready to verify with the prebuilt addin provided or from daily after the PR merge.

**Comment by Dbarnes1** [comment]
verified fixed.
