### ISSUE TITLE
Symbol Editor Add-in doesn't work with SDE Military Overlay

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/military-symbol-editor-addin-wpf#97]
Currently, the Military Overlay template has a workflow where users
1. are editing symbolized features locally with a file geodatabase
2. decide that they would like to share their data out as editable feature services, so they store their data in an enterprise geodatabase. They do this by copying the data into their enterprise geodatabase and repointing the data source of the existing map layers to this new enterprise location. 

Once the data source of the map layers are referencing the enterprise geodatabase, the military symbol editor add-in no longer works. However, it also no longer throws any kind of error. I can search for symbols, edit the symbol and label attributes, but when i try and add them to the map, the symbol doesn't get added. 

Eventually, it would be nice to have the symbol editor add-in work with the military overlay schema in an enterprise GDB.

However, for the short term, we need some sort of warning to be built into the editor that says it only works with file geodatabases. 

If someone else could repro this case, that would be great.

**Comment by csmoore** [comment]
Using an SDE used to work (I believe @BobBooth [tested this](https://github.com/Esri/military-symbol-editor-addin-wpf/issues/55#issuecomment-223102133) ). Are you sure it is not the same issue reported in #96 where there are multiple military feature GDBs in a project and the addin is defaulting to the first one it finds (which may not be the one on the map).

Can you provide more detail on which GDB should be used in this scenario with multiple GDBs?

**Comment by Dbarnes1** [comment]
@csmoore this was my workflow that broke the symbol editor add-in.

1. I opened our new Military Overlay template, which has a file geodatabase for Bc2 and a file geodatabase for D. Symbol Editor works minus the confusion I reference in #96. 
2. I add the schema that is hosted on our nsec sde database to the project. I repoint the data layers of the 2525D map to reference the sde geodatabase. I then remove the 2525D file geodatabase. At this point, the symbol editor stops working. 

I guess the problem might be that I'm replacing the file geodatabase with the enterprise geodatabase, which is causing the symbol editor to break.

**Comment by csmoore** [comment]
@Dbarnes1 - OK I can test this scenario - please provide the SDE layer details (offline) when you get a chance

**Comment by elinz** [comment]
@csmoore I tested the symbol editor in the pull request #98 in a non-MilitaryOverlay template and it does not allow me to edit features in an enterprise geodatabase. 

I copied the Units file geodatabase from the 2525D file geodatabase associated with the Military Overlay Template to a PostgreSQL enterprise geodatabase; then added this enterprise geodatabase feature class to the active map, and then set the symbology to use the dictionary renderer. When I attempted to add an infantry unit to the map, I received the following error...
![image](https://cloud.githubusercontent.com/assets/4635490/19989903/e0217090-a1e6-11e6-956b-50c2e211a0f6.png)

The editor expects the feature classes containing the 2525 schema to be in the ArcGIS Pro project file geodatabase. This error is a **showstopper**; users have to be able to edit features in enterprise geodatabases.

**Comment by csmoore** [comment]
@elinz - thanks for the info - I can prioritize this existing issue after the PR if there are no objections. 

This is also sounds like potential another issue (in addition to the one first reported in this issue) of a known limit that there can only be one GDB per standard in the project (sounds like there are two 2525D ones - one FGDB and one EGDB - I would be curious if the behavior is different if the FGDB were removed)

**Comment by topowright** [comment]
I am unclear on what the desired end result is for this issue. If the only issue we are trying to solve is being able to write to a SDE database using the Military Overlay Template then we have accomplished solving this issue. The one concern if I am currently only working with the Military Symbol Editor (MSE) I do not have the ability to repoint the MSE to a already configured SDE. Without the Military Overlay Template I do not have the ability to create features inside of a SDE database.  

I think that this is going to be an issue for Military Tools for ArcGIS users who will want to edit their database holdings of military symbology. @lfunkhouser @nfeuerstein @Dbarnes1 @csmoore Please share your thoughts on these findings.

**Comment by csmoore** [comment]
If 1. the project you open has an EGDB(SDE) with the Military Overlay data model or 2. you add/replace a new EGDB in your project things should work. But I may not fully understand what you mean by repointing to a new Military Overlay EGDB.
________________________________

**Comment by topowright** [comment]
After discussing with @csmoore and @Dbarnes1 they set me straight. This issue has been fixed.

**Comment by topowright** [comment]
@Dbarnes1 please verify and close

**Comment by Dbarnes1** [comment]
@topowright thanks for taking a second look. Verified, closing.
