### ISSUE TITLE
Preview/Next button labels do not match what they do

### ISSUE THREAD

**Issue by elinz** [Esri/military-symbol-editor-addin-wpf#99]
Testing addin from pull request https://github.com/Esri/military-symbol-editor-addin-wpf/pull/98

Open Military Symbol Editor:
- When "Search" tab is active, Next button is labeled "Go to Modify Tab", but actually takes you to "Symbol" tab.
- When "Modify" tab is active, Next button is labeled "Go to Modify Tab". I'm already on the Modify tab. It takes you to "Symbol" tab.
- When "Symbol" tab is active, Next button is labeled "Text". It takes you to "Label" tab so change the Next button to "Go to Label Tab".
- When "Enter Coordinates" tab is active, the Previous button is labeled "Back to Text". change it to "Back to Label"

Review the previous/next buttons on all tabs and make sure they are labeled correctly.

Be consistent with tool tip names used on the previous/next buttons, for example some buttons use the term "Tab", ie. "Go to Modify Tab" and other buttons do not.

**Comment by csmoore** [comment]
Good catch - the tabs got renamed a while ago (pre-PR) but not the corresponding tooltips.  Addressed in https://github.com/Esri/military-symbol-editor-addin-wpf/pull/98/commits/3eca4f6863ed694d1cf496296355be40a40cd090

**Comment by csmoore** [comment]
Ready to verify - can be retested with the prebuilt addin provided or from daily after the PR merge.

**Comment by Dbarnes1** [comment]
@csmoore @elinz verified, closing.
